import { useCallback, useEffect, useState } from 'react';
import { CheckCircle2, Loader2, Plus, Save, Trash2 } from 'lucide-react';
import { supabase } from '../../../lib/supabase';
import { validateQuizDraft } from '../../../domain/quizAuthoring';

interface DraftOption { option_text: string; is_correct: boolean }
interface DraftQuestion { question_text: string; explanation: string; points: number; options: DraftOption[] }
interface DraftQuiz { title: string; description: string; pass_percentage: number; time_limit_minutes: number | null; max_attempts: number; is_published: boolean; questions: DraftQuestion[] }

const newQuestion = (): DraftQuestion => ({ question_text: '', explanation: '', points: 1, options: [{ option_text: '', is_correct: true }, { option_text: '', is_correct: false }] });

export function QuizBuilder({ lessonId, lessonTitle }: { lessonId: string; lessonTitle: string }) {
  const [quiz, setQuiz] = useState<DraftQuiz>({ title: lessonTitle, description: '', pass_percentage: 70, time_limit_minutes: null, max_attempts: 3, is_published: false, questions: [newQuestion()] });
  const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [message, setMessage] = useState('');
  const load = useCallback(async () => { const { data, error } = await supabase.rpc('get_author_quiz', { p_lesson_id: lessonId }); if (error) setMessage('The quiz could not be loaded.'); else if (data) setQuiz(data as DraftQuiz); setLoading(false); }, [lessonId]);
  useEffect(() => { void load(); }, [load]);
  const updateQuestion = (index: number, patch: Partial<DraftQuestion>) => setQuiz(value => ({ ...value, questions: value.questions.map((question, position) => position === index ? { ...question, ...patch } : question) }));
  const save = async () => { const errors = validateQuizDraft(quiz); if (errors.length) { setMessage(errors[0]); return; } setSaving(true); setMessage(''); const { error } = await supabase.rpc('author_save_quiz', { p_lesson_id: lessonId, p_quiz: quiz }); setSaving(false); setMessage(error ? error.message : 'Quiz saved. Attempt limits are enforced by the server.'); };
  if (loading) return <div role="status" className="flex items-center gap-2 rounded-xl border p-5"><Loader2 className="h-5 w-5 animate-spin" />Loading quiz builder…</div>;
  return <section aria-labelledby="quiz-builder-heading" className="space-y-6 rounded-2xl border border-amber-200 bg-amber-50/40 p-4 sm:p-6">
    <div><p className="text-sm font-bold text-amber-700">Assessment</p><h3 id="quiz-builder-heading" className="text-xl font-bold text-primary-900">Quiz builder</h3><p className="mt-1 text-sm text-primary-600">Create single-choice questions. Students can retry up to the limit configured here.</p></div>
    {message && <p role="status" className="rounded-xl bg-white p-3 text-sm font-medium text-primary-700">{message}</p>}
    <div className="grid gap-4 md:grid-cols-3"><label className="text-sm font-bold">Pass score (%)<input type="number" min="1" max="100" value={quiz.pass_percentage} onChange={event => setQuiz(value => ({ ...value, pass_percentage: Number(event.target.value) }))} className="mt-2 min-h-11 w-full rounded-xl border p-3" /></label><label className="text-sm font-bold">Maximum attempts<input type="number" min="1" max="20" value={quiz.max_attempts} onChange={event => setQuiz(value => ({ ...value, max_attempts: Number(event.target.value) }))} className="mt-2 min-h-11 w-full rounded-xl border p-3" /></label><label className="text-sm font-bold">Time limit (minutes)<input type="number" min="1" value={quiz.time_limit_minutes ?? ''} placeholder="No limit" onChange={event => setQuiz(value => ({ ...value, time_limit_minutes: event.target.value ? Number(event.target.value) : null }))} className="mt-2 min-h-11 w-full rounded-xl border p-3" /></label></div>
    <label className="block text-sm font-bold">Quiz instructions<textarea rows={3} value={quiz.description} onChange={event => setQuiz(value => ({ ...value, description: event.target.value }))} className="mt-2 w-full rounded-xl border p-3 font-normal" /></label>
    <div className="space-y-4">{quiz.questions.map((question, questionIndex) => <fieldset key={questionIndex} className="rounded-2xl border bg-white p-4 sm:p-5"><legend className="px-2 font-bold text-primary-900">Question {questionIndex + 1}</legend><div className="flex gap-2"><textarea aria-label={`Question ${questionIndex + 1} text`} rows={2} value={question.question_text} onChange={event => updateQuestion(questionIndex, { question_text: event.target.value })} placeholder="Enter a clear question" className="w-full rounded-xl border p-3" /><button type="button" aria-label={`Remove question ${questionIndex + 1}`} disabled={quiz.questions.length === 1} onClick={() => setQuiz(value => ({ ...value, questions: value.questions.filter((_, index) => index !== questionIndex) }))} className="h-11 w-11 flex-none rounded-xl text-danger-600 disabled:opacity-30"><Trash2 className="mx-auto h-5 w-5" /></button></div><div className="mt-4 space-y-2">{question.options.map((option, optionIndex) => <label key={optionIndex} className="flex min-h-11 items-center gap-3 rounded-xl border p-2"><input type="radio" name={`correct-${questionIndex}`} checked={option.is_correct} onChange={() => updateQuestion(questionIndex, { options: question.options.map((item, index) => ({ ...item, is_correct: index === optionIndex })) })} aria-label={`Mark answer ${optionIndex + 1} correct`} /><input aria-label={`Answer ${optionIndex + 1}`} value={option.option_text} onChange={event => updateQuestion(questionIndex, { options: question.options.map((item, index) => index === optionIndex ? { ...item, option_text: event.target.value } : item) })} placeholder={`Answer ${optionIndex + 1}`} className="min-h-10 flex-1 border-0 bg-transparent p-2" /><button type="button" aria-label={`Remove answer ${optionIndex + 1}`} disabled={question.options.length === 2} onClick={() => updateQuestion(questionIndex, { options: question.options.filter((_, index) => index !== optionIndex) })}><Trash2 className="h-4 w-4 text-primary-400" /></button></label>)}</div><button type="button" onClick={() => updateQuestion(questionIndex, { options: [...question.options, { option_text: '', is_correct: false }] })} className="mt-3 inline-flex min-h-11 items-center gap-2 rounded-xl px-3 text-sm font-bold text-primary-700"><Plus className="h-4 w-4" />Add answer</button><label className="mt-3 block text-sm font-bold">Answer explanation<textarea rows={2} value={question.explanation} onChange={event => updateQuestion(questionIndex, { explanation: event.target.value })} className="mt-2 w-full rounded-xl border p-3 font-normal" /></label></fieldset>)}</div>
    <button type="button" onClick={() => setQuiz(value => ({ ...value, questions: [...value.questions, newQuestion()] }))} className="inline-flex min-h-11 items-center gap-2 rounded-xl border bg-white px-4 font-bold"><Plus className="h-4 w-4" />Add question</button>
    <div className="flex flex-col gap-3 border-t pt-5 sm:flex-row sm:items-center sm:justify-between"><label className="flex min-h-11 items-center gap-3 font-bold"><input type="checkbox" checked={quiz.is_published} onChange={event => setQuiz(value => ({ ...value, is_published: event.target.checked }))} />Available to students</label><button type="button" disabled={saving} onClick={() => void save()} className="inline-flex min-h-11 items-center justify-center gap-2 rounded-xl bg-primary-900 px-5 font-bold text-white disabled:opacity-50">{saving ? <Loader2 className="h-4 w-4 animate-spin" /> : <Save className="h-4 w-4" />}Save quiz</button></div><p className="flex items-center gap-2 text-xs text-primary-500"><CheckCircle2 className="h-4 w-4 text-success-600" />Exactly one correct answer is required per question. Answer keys are never sent before submission.</p>
  </section>;
}
