import { FormEvent, useEffect, useRef, useState } from 'react';
import { GraduationCap, Loader2, Menu, ShieldCheck } from 'lucide-react';
import { PortalLayout } from '../components/layout/PortalLayout';
import { Sidebar } from '../components/dashboard/Sidebar';
import { Button } from '../components/ui/Button';
import { Input } from '../components/ui/Input';
import { supabase } from '../lib/supabase';
import { useAuth } from '../contexts/AuthContext';

const EXPERTISE = ['Skin care', 'Hair care', 'Cosmetic science', 'Professional practice'];

export function InstructorApplication() {
  const { refreshSession } = useAuth();
  const lastStatusRef = useRef<string | null>(null);
  const [sidebar, setSidebar] = useState(false);
  const [application, setApplication] = useState<any>(null);
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);
  const [name, setName] = useState(''); const [bio, setBio] = useState(''); const [credentials, setCredentials] = useState(''); const [portfolio, setPortfolio] = useState(''); const [expertise, setExpertise] = useState<string[]>([]); const [message, setMessage] = useState('');
  useEffect(() => { let active=true; const load=async()=>{ const { data }=await supabase.from('instructor_applications').select('*').maybeSingle(); if(!active)return; setApplication(data); if(data){ setName(data.professional_name); setBio(data.bio); setCredentials(data.credentials); setPortfolio(data.portfolio_url||''); setExpertise(data.expertise||[]); if(data.status!==lastStatusRef.current&&['approved','suspended','rejected'].includes(data.status)) await refreshSession().catch(()=>undefined); lastStatusRef.current=data.status; } setLoading(false); }; void load(); const timer=window.setInterval(()=>void load(),15000); return()=>{active=false;clearInterval(timer);}; }, [refreshSession]);
  const submit = async (event: FormEvent) => { event.preventDefault(); if (bio.trim().length < 80 || credentials.trim().length < 20 || expertise.length === 0) { setMessage('Add at least one expertise area, an 80-character biography, and 20 characters of credentials.'); return; } setSaving(true); setMessage(''); const { error } = await supabase.rpc('submit_instructor_application', { p_professional_name: name, p_bio: bio, p_expertise: expertise, p_credentials: credentials, p_portfolio_url: portfolio }); setSaving(false); if (error) setMessage(error.message); else { setMessage('Your instructor application was submitted for admin review.'); setApplication({ status: 'submitted' }); } };
  return <PortalLayout sidebar={<Sidebar isOpen={sidebar} setIsOpen={setSidebar} />} mobileNavigationTrigger={<button type="button" aria-label="Open navigation" onClick={() => setSidebar(true)} className="fixed right-4 top-4 z-40 flex h-11 w-11 items-center justify-center rounded-xl border bg-white lg:hidden"><Menu /></button>}>
    <header className="mb-8"><p className="font-bold text-accent-700">Teach on Tutiba</p><h1 className="mt-1 text-3xl font-bold text-primary-900">Instructor application</h1><p className="mt-2 max-w-2xl text-primary-600">Applications are reviewed by an administrator. Approval is required before you can create courses, and only admins can publish them.</p></header>
    {loading ? <Loader2 className="mx-auto h-8 w-8 animate-spin" /> : application?.status === 'approved' ? <div className="rounded-2xl border border-success-200 bg-success-100 p-8 text-center"><ShieldCheck className="mx-auto mb-3 h-12 w-12 text-success-700" /><h2 className="text-xl font-bold text-primary-900">You are an approved instructor</h2><p className="mt-2 text-primary-600">Your instructor tools are now available without signing in again.</p></div> : <form onSubmit={submit} className="space-y-6 rounded-3xl border border-primary-200 bg-white p-6 shadow-sm md:p-9">{application?.status && <div className="rounded-xl bg-amber-50 p-4 text-sm font-bold text-amber-800">Application status: {String(application.status).replace('_', ' ')}{application.reviewer_notes && <p className="mt-2 font-normal">Reviewer feedback: {application.reviewer_notes}</p>}</div>}{message && <p role="status" className="rounded-xl bg-primary-50 p-4 text-sm text-primary-700">{message}</p>}<Input label="Professional display name" value={name} onChange={event => setName(event.target.value)} required minLength={2} /><div><label className="mb-2 block text-sm font-bold">Professional biography</label><textarea value={bio} onChange={event => setBio(event.target.value)} rows={6} required className="w-full rounded-xl border border-primary-200 p-3" /><p className="text-xs text-primary-500">{bio.length}/80 minimum characters</p></div><fieldset><legend className="mb-2 text-sm font-bold">Expertise</legend><div className="grid gap-2 sm:grid-cols-2">{EXPERTISE.map(item => <label key={item} className="flex min-h-11 items-center gap-3 rounded-xl border p-3"><input type="checkbox" checked={expertise.includes(item)} onChange={event => setExpertise(values => event.target.checked ? [...values, item] : values.filter(value => value !== item))} />{item}</label>)}</div></fieldset><div><label className="mb-2 block text-sm font-bold">Credentials and experience</label><textarea value={credentials} onChange={event => setCredentials(event.target.value)} rows={4} required className="w-full rounded-xl border border-primary-200 p-3" /></div><Input label="Portfolio or professional profile URL (optional)" type="url" value={portfolio} onChange={event => setPortfolio(event.target.value)} /><Button type="submit" isLoading={saving} disabled={saving || !['changes_requested','rejected'].includes(application?.status) && Boolean(application)} icon={<GraduationCap className="h-4 w-4" />}>{application ? 'Resubmit for review' : 'Submit for review'}</Button></form>}
  </PortalLayout>;
}
