import { useCallback, useEffect, useState } from 'react';
import { CheckCircle2, ClipboardCheck, Loader2, Send } from 'lucide-react';
import { supabase } from '../../lib/supabase';

interface Assignment { id: string; instructions: string; due_at: string | null; max_points: number; allowed_submission: 'text' | 'link' | 'text_or_link'; submission: null | { status: string; submission_text: string | null; submission_url: string | null; score: number | null; feedback: string | null; submitted_at: string } }

export function AssignmentLessonRenderer({ lessonId }: { lessonId: string }) {
  const [assignment, setAssignment] = useState<Assignment | null>(null); const [text, setText] = useState(''); const [url, setUrl] = useState(''); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [message, setMessage] = useState('');
  const load = useCallback(async () => { const { data, error } = await supabase.rpc('get_assignment_for_lesson', { p_lesson_id: lessonId }); setAssignment((data || null) as Assignment | null); if (error || !data) setMessage('This assignment is not available yet.'); setLoading(false); }, [lessonId]);
  useEffect(() => { void load(); }, [load]);
  const submit = async () => { if (!assignment) return; setSaving(true); const { error } = await supabase.rpc('submit_assignment', { p_assignment_id: assignment.id, p_text: text, p_url: url }); setSaving(false); if (error) setMessage(error.message); else { setMessage('Assignment submitted for review.'); await load(); } };
  if (loading) return <div role="status" className="rounded-2xl border bg-white p-8 text-center"><Loader2 className="mx-auto h-7 w-7 animate-spin" /></div>;
  if (!assignment) return <div role="alert" className="rounded-2xl border bg-white p-8 text-center">{message}</div>;
  const canRevise = !assignment.submission || assignment.submission.status === 'needs_revision';
  return <section aria-labelledby="assignment-heading" className="rounded-2xl border bg-white p-5 shadow-sm sm:p-8"><div className="flex items-start gap-3"><ClipboardCheck className="h-7 w-7 flex-none text-teal-600" /><div><h2 id="assignment-heading" className="text-2xl font-bold">Assignment</h2><p className="mt-1 text-sm text-primary-500">{assignment.max_points} points{assignment.due_at ? ` · Due ${new Date(assignment.due_at).toLocaleString()}` : ' · No deadline'}</p></div></div><div className="mt-6 whitespace-pre-wrap rounded-xl bg-primary-50 p-4 leading-relaxed">{assignment.instructions}</div>{message && <p role="status" className="mt-4 rounded-xl bg-amber-50 p-3 text-sm">{message}</p>}{assignment.submission && <div className="mt-5 rounded-xl border border-success-200 bg-success-100 p-4"><p className="flex items-center gap-2 font-bold"><CheckCircle2 className="h-5 w-5" />Status: {assignment.submission.status.replace('_', ' ')}</p>{assignment.submission.score !== null && <p className="mt-2">Score: {assignment.submission.score}/{assignment.max_points}</p>}{assignment.submission.feedback && <p className="mt-2"><strong>Instructor feedback:</strong> {assignment.submission.feedback}</p>}</div>}{canRevise && <div className="mt-6 space-y-4">{assignment.allowed_submission !== 'link' && <label className="block text-sm font-bold">Your response<textarea rows={7} value={text} onChange={event => setText(event.target.value)} className="mt-2 w-full rounded-xl border p-3 font-normal" /></label>}{assignment.allowed_submission !== 'text' && <label className="block text-sm font-bold">Secure work link<input type="url" value={url} onChange={event => setUrl(event.target.value)} placeholder="https://…" className="mt-2 min-h-11 w-full rounded-xl border p-3 font-normal" /></label>}<button type="button" disabled={saving} onClick={() => void submit()} className="inline-flex min-h-11 w-full items-center justify-center gap-2 rounded-xl bg-primary-900 px-5 font-bold text-white sm:w-auto">{saving ? <Loader2 className="h-4 w-4 animate-spin" /> : <Send className="h-4 w-4" />}{assignment.submission ? 'Resubmit assignment' : 'Submit assignment'}</button></div>}</section>;
}
