-- Phase 7: audited review gate and readiness-enforced publication.
BEGIN;
CREATE TABLE public.course_review_events(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),course_id UUID NOT NULL REFERENCES public.courses(id) ON DELETE RESTRICT,actor_id UUID NOT NULL REFERENCES public.users(id) ON DELETE RESTRICT,event_type TEXT NOT NULL CHECK(event_type IN('submitted','changes_requested','approved','rejected','published','unpublished')),notes TEXT NULL,created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE INDEX course_review_events_course_created_idx ON public.course_review_events(course_id,created_at DESC);
ALTER TABLE public.course_review_events ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Authors view own course review history" ON public.course_review_events FOR SELECT TO authenticated USING(EXISTS(SELECT 1 FROM public.courses c WHERE c.id=course_id AND c.author_id=auth.uid()));
CREATE POLICY "Admins view all course review history" ON public.course_review_events FOR SELECT TO authenticated USING(public.is_admin());

CREATE FUNCTION public.get_course_readiness(p_course_id UUID) RETURNS JSONB LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path=public AS $$
DECLARE c public.courses; v_sections INT; v_lessons INT; v_invalid INT; v_checks JSONB;
BEGIN
 SELECT * INTO c FROM public.courses WHERE id=p_course_id;
 IF c.id IS NULL OR NOT (public.is_admin() OR c.author_id=auth.uid()) THEN RAISE EXCEPTION USING ERRCODE='42501',MESSAGE='Course access required'; END IF;
 SELECT count(*) INTO v_sections FROM public.course_sections WHERE course_id=c.id AND deleted_at IS NULL;
 SELECT count(*) INTO v_lessons FROM public.lessons WHERE course_id=c.id AND deleted_at IS NULL;
 SELECT count(*) INTO v_invalid FROM public.lessons l WHERE l.course_id=c.id AND l.deleted_at IS NULL AND ((l.content_type='video' AND COALESCE(l.video_metadata_status,'failed') NOT IN('ready','unavailable')) OR (l.content_type='quiz' AND NOT EXISTS(SELECT 1 FROM public.quizzes q WHERE q.lesson_id=l.id AND q.is_published)) OR (l.content_type='assignment' AND NOT EXISTS(SELECT 1 FROM public.assignment_definitions a WHERE a.lesson_id=l.id AND a.is_published)));
 v_checks:=jsonb_build_array(jsonb_build_object('key','title','label','Course title','complete',char_length(trim(c.title))>=3),jsonb_build_object('key','description','label','Course description','complete',char_length(trim(COALESCE(c.description,'')))>=40),jsonb_build_object('key','cover','label','Managed cover image','complete',COALESCE(c.cover_image,c.thumbnail) IS NOT NULL),jsonb_build_object('key','pricing','label','Regional pricing','complete',c.price_egp IS NOT NULL AND c.price_usd IS NOT NULL),jsonb_build_object('key','instructor','label','Approved instructor','complete',c.instructor_id IS NOT NULL AND public.is_approved_instructor(c.instructor_id)),jsonb_build_object('key','sections','label','At least one section','complete',v_sections>0),jsonb_build_object('key','lessons','label','At least one lesson','complete',v_lessons>0),jsonb_build_object('key','content','label','Lesson content is ready','complete',v_invalid=0));
 RETURN jsonb_build_object('ready',NOT EXISTS(SELECT 1 FROM jsonb_array_elements(v_checks) x WHERE NOT (x->>'complete')::boolean),'checks',v_checks,'review_status',c.review_status,'authoring_status',c.authoring_status,'status',c.status,'reviewer_notes',(SELECT notes FROM public.course_review_events WHERE course_id=c.id AND event_type IN('changes_requested','rejected') ORDER BY created_at DESC LIMIT 1));
END $$;
CREATE FUNCTION public.submit_course_for_review(p_course_id UUID,p_notes TEXT DEFAULT NULL) RETURNS VOID LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$
DECLARE c public.courses; readiness JSONB;
BEGIN SELECT * INTO c FROM public.courses WHERE id=p_course_id FOR UPDATE; IF c.author_id<>auth.uid() OR NOT public.is_approved_instructor(auth.uid()) THEN RAISE EXCEPTION USING ERRCODE='42501',MESSAGE='Approved course owner required'; END IF; IF c.authoring_status<>'draft' OR c.review_status NOT IN('not_submitted','changes_requested','rejected') THEN RAISE EXCEPTION USING ERRCODE='22023',MESSAGE='Course cannot be submitted from its current state'; END IF; readiness:=public.get_course_readiness(p_course_id); IF NOT (readiness->>'ready')::boolean THEN RAISE EXCEPTION USING ERRCODE='23514',MESSAGE='Complete every readiness check before submission'; END IF; UPDATE public.courses SET authoring_status='in_review',review_status='submitted',updated_at=now() WHERE id=p_course_id; INSERT INTO public.course_review_events(course_id,actor_id,event_type,notes) VALUES(p_course_id,auth.uid(),'submitted',nullif(trim(p_notes),'')); END $$;
CREATE FUNCTION public.admin_decide_course_review(p_course_id UUID,p_decision TEXT,p_notes TEXT) RETURNS VOID LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$
DECLARE c public.courses;
BEGIN IF NOT public.is_admin() THEN RAISE EXCEPTION USING ERRCODE='42501',MESSAGE='Admin access required'; END IF; IF p_decision NOT IN('approved','changes_requested','rejected') THEN RAISE EXCEPTION USING ERRCODE='22023',MESSAGE='Invalid review decision'; END IF; IF p_decision<>'approved' AND char_length(trim(COALESCE(p_notes,'')))<5 THEN RAISE EXCEPTION USING ERRCODE='22023',MESSAGE='Actionable review notes are required'; END IF; SELECT * INTO c FROM public.courses WHERE id=p_course_id FOR UPDATE; IF c.review_status<>'submitted' THEN RAISE EXCEPTION USING ERRCODE='22023',MESSAGE='Only submitted courses can be reviewed'; END IF; UPDATE public.courses SET authoring_status=CASE WHEN p_decision='approved' THEN 'approved' ELSE 'draft' END,review_status=p_decision,updated_at=now() WHERE id=p_course_id; INSERT INTO public.course_review_events(course_id,actor_id,event_type,notes) VALUES(p_course_id,auth.uid(),p_decision,nullif(trim(p_notes),'')); END $$;
CREATE FUNCTION public.admin_set_course_publication(p_course_id UUID,p_publish BOOLEAN) RETURNS VOID LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$
DECLARE c public.courses;
BEGIN IF NOT public.is_admin() THEN RAISE EXCEPTION USING ERRCODE='42501',MESSAGE='Admin access required'; END IF; SELECT * INTO c FROM public.courses WHERE id=p_course_id FOR UPDATE; IF p_publish AND (c.authoring_status<>'approved' OR c.review_status<>'approved') THEN RAISE EXCEPTION USING ERRCODE='23514',MESSAGE='Course approval is required before publication'; END IF; UPDATE public.courses SET status=CASE WHEN p_publish THEN 'published' ELSE 'draft' END,published_at=CASE WHEN p_publish THEN COALESCE(published_at,now()) ELSE published_at END,updated_at=now() WHERE id=p_course_id; INSERT INTO public.course_review_events(course_id,actor_id,event_type) VALUES(p_course_id,auth.uid(),CASE WHEN p_publish THEN 'published' ELSE 'unpublished' END); END $$;
CREATE FUNCTION public.admin_list_course_reviews() RETURNS TABLE(course_id UUID,title TEXT,author_name TEXT,submitted_at TIMESTAMPTZ) LANGUAGE sql STABLE SECURITY DEFINER SET search_path=public AS $$ SELECT c.id,c.title,u.full_name,(SELECT max(e.created_at) FROM public.course_review_events e WHERE e.course_id=c.id AND e.event_type='submitted') FROM public.courses c LEFT JOIN public.users u ON u.id=c.author_id WHERE public.is_admin() AND c.review_status='submitted' ORDER BY 4; $$;
REVOKE ALL ON FUNCTION public.get_course_readiness(UUID),public.submit_course_for_review(UUID,TEXT),public.admin_decide_course_review(UUID,TEXT,TEXT),public.admin_set_course_publication(UUID,BOOLEAN),public.admin_list_course_reviews() FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.get_course_readiness(UUID),public.submit_course_for_review(UUID,TEXT),public.admin_decide_course_review(UUID,TEXT,TEXT),public.admin_set_course_publication(UUID,BOOLEAN),public.admin_list_course_reviews() TO authenticated;
COMMIT;
