-- Tutiba course-review feature: one-time complete database rollout.
-- Generated by: node scripts/build-database-rollout.mjs
-- Baseline required: all repository migrations through 20260730000001.
-- This is the ONLY database script required when no July 30 phase script has been run.
-- Paste this entire file into the Supabase SQL editor and run it ONCE.
-- All nine phases and the postflight are one transaction: any error rolls everything back.

BEGIN;
DO $$ BEGIN
 IF to_regclass('public.courses') IS NULL OR to_regclass('public.instructor_applications') IS NULL OR to_regclass('public.course_review_events') IS NULL THEN
  RAISE EXCEPTION 'Required baseline is missing. Apply repository migrations through 20260730000001 first.';
 END IF;
 IF to_regclass('public.course_revisions') IS NOT NULL THEN
  RAISE EXCEPTION 'This feature rollout appears to have already started. Do not run the consolidated script over partial migrations.';
 END IF;
END $$;

-- ============================================================================
-- SOURCE: supabase/migrations/20260730010000_course_revision_lifecycle.sql
-- ============================================================================
-- Phase 1: immutable review revisions and database-enforced lifecycle invariants.

CREATE TABLE public.course_revisions (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  course_id UUID NOT NULL REFERENCES public.courses(id) ON DELETE RESTRICT,
  revision_number BIGINT NOT NULL,
  snapshot JSONB NOT NULL,
  content_hash TEXT NOT NULL,
  created_by UUID NOT NULL REFERENCES public.users(id) ON DELETE RESTRICT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (course_id, revision_number)
);
CREATE INDEX course_revisions_course_created_idx ON public.course_revisions(course_id, created_at DESC);
ALTER TABLE public.course_revisions ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Course authors view own revisions" ON public.course_revisions FOR SELECT TO authenticated
  USING (EXISTS (SELECT 1 FROM public.courses c WHERE c.id = course_id AND c.author_id = auth.uid()));
CREATE POLICY "Admins view course revisions" ON public.course_revisions FOR SELECT TO authenticated USING (public.is_admin());

ALTER TABLE public.courses
  ADD COLUMN submitted_revision_id UUID NULL REFERENCES public.course_revisions(id) ON DELETE RESTRICT,
  ADD COLUMN approved_revision_id UUID NULL REFERENCES public.course_revisions(id) ON DELETE RESTRICT;
ALTER TABLE public.course_review_events
  ADD COLUMN revision_id UUID NULL REFERENCES public.course_revisions(id) ON DELETE RESTRICT;

-- Normalize legacy rows before installing the cross-column state contract.
UPDATE public.courses SET
  authoring_status = CASE
    WHEN status = 'archived' THEN 'archived'
    WHEN status = 'published' OR review_status = 'approved' THEN 'approved'
    WHEN review_status = 'submitted' THEN 'in_review'
    ELSE 'draft'
  END,
  review_status = CASE
    WHEN status IN ('published', 'archived') OR review_status = 'approved' THEN 'approved'
    WHEN review_status = 'submitted' THEN 'submitted'
    WHEN review_status IN ('changes_requested', 'rejected') THEN review_status
    ELSE 'not_submitted'
  END;

ALTER TABLE public.courses DROP CONSTRAINT IF EXISTS courses_workflow_state_check;
ALTER TABLE public.courses ADD CONSTRAINT courses_workflow_state_check CHECK (
  (authoring_status = 'draft' AND review_status IN ('not_submitted', 'changes_requested', 'rejected') AND status IN ('draft', 'archived')) OR
  (authoring_status = 'in_review' AND review_status = 'submitted' AND status = 'draft') OR
  (authoring_status = 'approved' AND review_status = 'approved' AND status IN ('draft', 'published', 'archived')) OR
  (authoring_status = 'archived' AND review_status = 'approved' AND status = 'archived')
);

CREATE OR REPLACE FUNCTION public.course_snapshot(p_course_id UUID) RETURNS JSONB
LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public AS $$
  SELECT jsonb_build_object(
    'course', to_jsonb(c) - ARRAY['authoring_status','review_status','status','version','submitted_revision_id','approved_revision_id','created_at','updated_at','published_at','archived_at'],
    'sections', COALESCE((SELECT jsonb_agg(to_jsonb(s) - ARRAY['created_at','updated_at'] ORDER BY s.order_index, s.id) FROM public.course_sections s WHERE s.course_id=c.id AND s.deleted_at IS NULL), '[]'::jsonb),
    'lessons', COALESCE((SELECT jsonb_agg(to_jsonb(l) - ARRAY['version','created_at','updated_at','video_metadata_updated_at'] ORDER BY l.section_id, l.order_index, l.id) FROM public.lessons l WHERE l.course_id=c.id AND l.deleted_at IS NULL), '[]'::jsonb),
    'quizzes', COALESCE((SELECT jsonb_agg(to_jsonb(q) - ARRAY['created_at','updated_at'] ORDER BY q.lesson_id, q.id) FROM public.quizzes q WHERE q.course_id=c.id), '[]'::jsonb),
    'questions', COALESCE((SELECT jsonb_agg(to_jsonb(qn) - ARRAY['created_at','updated_at'] ORDER BY qn.quiz_id, qn.order_index, qn.id) FROM public.questions qn JOIN public.quizzes q ON q.id=qn.quiz_id WHERE q.course_id=c.id), '[]'::jsonb),
    'question_options', COALESCE((SELECT jsonb_agg(to_jsonb(o) - ARRAY['created_at','updated_at'] ORDER BY o.question_id, o.order_index, o.id) FROM public.question_options o JOIN public.questions qn ON qn.id=o.question_id JOIN public.quizzes q ON q.id=qn.quiz_id WHERE q.course_id=c.id), '[]'::jsonb),
    'assignments', COALESCE((SELECT jsonb_agg(to_jsonb(a) - ARRAY['created_at','updated_at'] ORDER BY a.lesson_id, a.id) FROM public.assignment_definitions a WHERE a.course_id=c.id), '[]'::jsonb)
  ) FROM public.courses c WHERE c.id=p_course_id AND (public.is_admin() OR c.author_id=auth.uid());
$$;

CREATE OR REPLACE FUNCTION public.create_course_revision(p_course_id UUID) RETURNS public.course_revisions
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE v_snapshot JSONB; v_revision public.course_revisions; v_number BIGINT;
BEGIN
  v_snapshot := public.course_snapshot(p_course_id);
  IF v_snapshot IS NULL THEN RAISE EXCEPTION USING ERRCODE='42501', MESSAGE='Course access required'; END IF;
  SELECT COALESCE(max(revision_number), 0) + 1 INTO v_number FROM public.course_revisions WHERE course_id=p_course_id;
  INSERT INTO public.course_revisions(course_id, revision_number, snapshot, content_hash, created_by)
  VALUES(p_course_id, v_number, v_snapshot, md5(v_snapshot::text), auth.uid()) RETURNING * INTO v_revision;
  RETURN v_revision;
END $$;

CREATE OR REPLACE FUNCTION public.assert_course_matches_revision(p_course_id UUID, p_revision_id UUID) RETURNS VOID
LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path = public AS $$
DECLARE v_expected TEXT; v_snapshot JSONB;
BEGIN
  SELECT content_hash INTO v_expected FROM public.course_revisions WHERE id=p_revision_id AND course_id=p_course_id;
  IF v_expected IS NULL THEN RAISE EXCEPTION USING ERRCODE='23514', MESSAGE='A valid course revision is required'; END IF;
  v_snapshot := public.course_snapshot(p_course_id);
  IF v_snapshot IS NULL OR md5(v_snapshot::text) <> v_expected THEN
    RAISE EXCEPTION USING ERRCODE='40001', MESSAGE='Course changed after submission; return it to draft and submit a new revision';
  END IF;
END $$;

CREATE OR REPLACE FUNCTION public.submit_course_for_review(p_course_id UUID,p_notes TEXT DEFAULT NULL) RETURNS VOID
LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$
DECLARE c public.courses; readiness JSONB; revision public.course_revisions;
BEGIN
  SELECT * INTO c FROM public.courses WHERE id=p_course_id FOR UPDATE;
  IF c.author_id<>auth.uid() OR NOT public.is_approved_instructor(auth.uid()) THEN RAISE EXCEPTION USING ERRCODE='42501',MESSAGE='Approved course owner required'; END IF;
  IF c.authoring_status<>'draft' OR c.review_status NOT IN('not_submitted','changes_requested','rejected') OR c.status='published' THEN RAISE EXCEPTION USING ERRCODE='22023',MESSAGE='Course cannot be submitted from its current state'; END IF;
  readiness:=public.get_course_readiness(p_course_id);
  IF NOT (readiness->>'ready')::boolean THEN RAISE EXCEPTION USING ERRCODE='23514',MESSAGE='Complete every readiness check before submission'; END IF;
  revision:=public.create_course_revision(p_course_id);
  UPDATE public.courses SET authoring_status='in_review',review_status='submitted',submitted_revision_id=revision.id,approved_revision_id=NULL,version=version+1,updated_at=now() WHERE id=p_course_id;
  INSERT INTO public.course_review_events(course_id,actor_id,event_type,notes,revision_id) VALUES(p_course_id,auth.uid(),'submitted',nullif(trim(p_notes),''),revision.id);
END $$;

CREATE OR REPLACE FUNCTION public.admin_decide_course_review(p_course_id UUID,p_decision TEXT,p_notes TEXT) RETURNS VOID
LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$
DECLARE c public.courses;
BEGIN
  IF NOT public.is_admin() THEN RAISE EXCEPTION USING ERRCODE='42501',MESSAGE='Admin access required'; END IF;
  IF p_decision NOT IN('approved','changes_requested','rejected') THEN RAISE EXCEPTION USING ERRCODE='22023',MESSAGE='Invalid review decision'; END IF;
  IF char_length(trim(COALESCE(p_notes,'')))<5 THEN RAISE EXCEPTION USING ERRCODE='22023',MESSAGE='A review note of at least 5 characters is required for every decision'; END IF;
  SELECT * INTO c FROM public.courses WHERE id=p_course_id FOR UPDATE;
  IF c.authoring_status<>'in_review' OR c.review_status<>'submitted' OR c.submitted_revision_id IS NULL THEN RAISE EXCEPTION USING ERRCODE='22023',MESSAGE='Only a submitted course revision can be reviewed'; END IF;
  PERFORM public.assert_course_matches_revision(p_course_id,c.submitted_revision_id);
  UPDATE public.courses SET authoring_status=CASE WHEN p_decision='approved' THEN 'approved' ELSE 'draft' END,review_status=p_decision,
    approved_revision_id=CASE WHEN p_decision='approved' THEN submitted_revision_id ELSE NULL END,version=version+1,updated_at=now() WHERE id=p_course_id;
  INSERT INTO public.course_review_events(course_id,actor_id,event_type,notes,revision_id) VALUES(p_course_id,auth.uid(),p_decision,trim(p_notes),c.submitted_revision_id);
END $$;

CREATE OR REPLACE FUNCTION public.admin_set_course_publication(p_course_id UUID,p_publish BOOLEAN) RETURNS VOID
LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$
DECLARE c public.courses;
BEGIN
  IF NOT public.is_admin() THEN RAISE EXCEPTION USING ERRCODE='42501',MESSAGE='Admin access required'; END IF;
  SELECT * INTO c FROM public.courses WHERE id=p_course_id FOR UPDATE;
  IF p_publish THEN
    IF c.authoring_status<>'approved' OR c.review_status<>'approved' OR c.approved_revision_id IS NULL THEN RAISE EXCEPTION USING ERRCODE='23514',MESSAGE='An approved course revision is required before publication'; END IF;
    PERFORM public.assert_course_matches_revision(p_course_id,c.approved_revision_id);
  ELSIF c.status<>'published' THEN
    RETURN;
  END IF;
  UPDATE public.courses SET status=CASE WHEN p_publish THEN 'published' ELSE 'draft' END,published_at=CASE WHEN p_publish THEN COALESCE(published_at,now()) ELSE published_at END,version=version+1,updated_at=now() WHERE id=p_course_id;
  INSERT INTO public.course_review_events(course_id,actor_id,event_type,revision_id) VALUES(p_course_id,auth.uid(),CASE WHEN p_publish THEN 'published' ELSE 'unpublished' END,c.approved_revision_id);
END $$;

REVOKE ALL ON FUNCTION public.course_snapshot(UUID), public.create_course_revision(UUID), public.assert_course_matches_revision(UUID,UUID) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.course_snapshot(UUID) TO authenticated;
REVOKE ALL ON FUNCTION public.submit_course_for_review(UUID,TEXT), public.admin_decide_course_review(UUID,TEXT,TEXT), public.admin_set_course_publication(UUID,BOOLEAN) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.submit_course_for_review(UUID,TEXT), public.admin_decide_course_review(UUID,TEXT,TEXT), public.admin_set_course_publication(UUID,BOOLEAN) TO authenticated;

NOTIFY pgrst, 'reload schema';


-- ============================================================================
-- SOURCE: supabase/migrations/20260730020000_course_readiness_and_concurrency.sql
-- ============================================================================
-- Phase 2: comprehensive publishability checks and serialized review decisions.

CREATE OR REPLACE FUNCTION public.lock_course_workflow(p_course_id UUID) RETURNS VOID
LANGUAGE plpgsql VOLATILE SECURITY DEFINER SET search_path=public AS $$
BEGIN
  IF p_course_id IS NULL THEN RAISE EXCEPTION USING ERRCODE='22023', MESSAGE='Course ID is required'; END IF;
  PERFORM pg_advisory_xact_lock(hashtextextended(p_course_id::text, 0));
END $$;

-- Every content mutation takes the same transaction lock as submit, review, and
-- publication. A child-row write can therefore never race past a decision.
CREATE OR REPLACE FUNCTION public.lock_course_content_mutation() RETURNS TRIGGER
LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$
DECLARE v_course_id UUID; v_row_id UUID;
BEGIN
  IF TG_TABLE_NAME='courses' THEN
    v_course_id:=CASE WHEN TG_OP='DELETE' THEN OLD.id ELSE NEW.id END;
  ELSIF TG_TABLE_NAME IN ('course_sections','lessons','quizzes','assignment_definitions') THEN
    v_course_id:=CASE WHEN TG_OP='DELETE' THEN OLD.course_id ELSE NEW.course_id END;
  ELSIF TG_TABLE_NAME='questions' THEN
    v_row_id:=CASE WHEN TG_OP='DELETE' THEN OLD.quiz_id ELSE NEW.quiz_id END;
    SELECT course_id INTO v_course_id FROM public.quizzes WHERE id=v_row_id;
  ELSIF TG_TABLE_NAME='question_options' THEN
    v_row_id:=CASE WHEN TG_OP='DELETE' THEN OLD.question_id ELSE NEW.question_id END;
    SELECT q.course_id INTO v_course_id FROM public.questions qn JOIN public.quizzes q ON q.id=qn.quiz_id WHERE qn.id=v_row_id;
  END IF;
  IF v_course_id IS NULL THEN RAISE EXCEPTION USING ERRCODE='23514', MESSAGE='Course content must belong to a course'; END IF;
  PERFORM public.lock_course_workflow(v_course_id);
  IF TG_OP='DELETE' THEN RETURN OLD; END IF;
  RETURN NEW;
END $$;

DROP TRIGGER IF EXISTS trg_courses_workflow_lock ON public.courses;
CREATE TRIGGER trg_courses_workflow_lock BEFORE INSERT OR UPDATE OR DELETE ON public.courses FOR EACH ROW EXECUTE FUNCTION public.lock_course_content_mutation();
DROP TRIGGER IF EXISTS trg_sections_workflow_lock ON public.course_sections;
CREATE TRIGGER trg_sections_workflow_lock BEFORE INSERT OR UPDATE OR DELETE ON public.course_sections FOR EACH ROW EXECUTE FUNCTION public.lock_course_content_mutation();
DROP TRIGGER IF EXISTS trg_lessons_workflow_lock ON public.lessons;
CREATE TRIGGER trg_lessons_workflow_lock BEFORE INSERT OR UPDATE OR DELETE ON public.lessons FOR EACH ROW EXECUTE FUNCTION public.lock_course_content_mutation();
DROP TRIGGER IF EXISTS trg_quizzes_workflow_lock ON public.quizzes;
CREATE TRIGGER trg_quizzes_workflow_lock BEFORE INSERT OR UPDATE OR DELETE ON public.quizzes FOR EACH ROW EXECUTE FUNCTION public.lock_course_content_mutation();
DROP TRIGGER IF EXISTS trg_questions_workflow_lock ON public.questions;
CREATE TRIGGER trg_questions_workflow_lock BEFORE INSERT OR UPDATE OR DELETE ON public.questions FOR EACH ROW EXECUTE FUNCTION public.lock_course_content_mutation();
DROP TRIGGER IF EXISTS trg_question_options_workflow_lock ON public.question_options;
CREATE TRIGGER trg_question_options_workflow_lock BEFORE INSERT OR UPDATE OR DELETE ON public.question_options FOR EACH ROW EXECUTE FUNCTION public.lock_course_content_mutation();
DROP TRIGGER IF EXISTS trg_assignments_workflow_lock ON public.assignment_definitions;
CREATE TRIGGER trg_assignments_workflow_lock BEFORE INSERT OR UPDATE OR DELETE ON public.assignment_definitions FOR EACH ROW EXECUTE FUNCTION public.lock_course_content_mutation();

CREATE OR REPLACE FUNCTION public.get_course_readiness(p_course_id UUID) RETURNS JSONB
LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path=public AS $$
DECLARE
  c public.courses; v_checks JSONB; v_published_sections INT; v_published_lessons INT;
  v_orphans INT; v_invalid_content INT; v_order_conflicts INT; v_invalid_quizzes INT;
BEGIN
  SELECT * INTO c FROM public.courses WHERE id=p_course_id;
  IF c.id IS NULL OR NOT (public.is_admin() OR c.author_id=auth.uid()) THEN RAISE EXCEPTION USING ERRCODE='42501', MESSAGE='Course access required'; END IF;

  SELECT count(*) INTO v_published_sections FROM public.course_sections WHERE course_id=c.id AND deleted_at IS NULL AND is_published;
  SELECT count(*) INTO v_published_lessons FROM public.lessons l JOIN public.course_sections s ON s.id=l.section_id
    WHERE l.course_id=c.id AND l.deleted_at IS NULL AND l.is_published AND s.deleted_at IS NULL AND s.is_published;
  SELECT count(*) INTO v_orphans FROM public.lessons l LEFT JOIN public.course_sections s ON s.id=l.section_id AND s.deleted_at IS NULL
    WHERE l.course_id=c.id AND l.deleted_at IS NULL AND (l.section_id IS NULL OR s.id IS NULL OR s.course_id<>c.id);
  SELECT count(*) INTO v_order_conflicts FROM (
    SELECT order_index FROM public.course_sections WHERE course_id=c.id AND deleted_at IS NULL GROUP BY order_index HAVING count(*)>1
    UNION ALL
    SELECT l.order_index FROM public.lessons l WHERE l.course_id=c.id AND l.deleted_at IS NULL GROUP BY l.section_id,l.order_index HAVING count(*)>1
  ) conflicts;
  SELECT count(*) INTO v_invalid_quizzes FROM public.quizzes q JOIN public.lessons l ON l.id=q.lesson_id
    WHERE q.course_id=c.id AND l.deleted_at IS NULL AND l.is_published AND (
      NOT q.is_published OR NOT EXISTS(SELECT 1 FROM public.questions qn WHERE qn.quiz_id=q.id AND qn.is_published) OR
      EXISTS(SELECT 1 FROM public.questions qn WHERE qn.quiz_id=q.id AND qn.is_published AND
        ((SELECT count(*) FROM public.question_options o WHERE o.question_id=qn.id)<2 OR
         (SELECT count(*) FROM public.question_options o WHERE o.question_id=qn.id AND o.is_correct)<>1))
    );
  SELECT count(*) INTO v_invalid_content FROM public.lessons l JOIN public.course_sections s ON s.id=l.section_id
    WHERE l.course_id=c.id AND l.deleted_at IS NULL AND l.is_published AND s.deleted_at IS NULL AND s.is_published AND (
      l.content_type IS NULL OR
      (l.content_type='video' AND (nullif(trim(l.video_url),'') IS NULL OR l.video_metadata_status IS DISTINCT FROM 'ready' OR COALESCE(l.video_duration_seconds,0)<=0)) OR
      (l.content_type='pdf' AND COALESCE(l.content_url,'') !~ '^https://[^[:space:]]+$') OR
      (l.content_type='external_link' AND COALESCE(l.content_url,'') !~ '^https://[^[:space:]]+$') OR
      (l.content_type='quiz' AND NOT EXISTS(SELECT 1 FROM public.quizzes q WHERE q.lesson_id=l.id AND q.is_published)) OR
      (l.content_type='assignment' AND NOT EXISTS(SELECT 1 FROM public.assignment_definitions a WHERE a.lesson_id=l.id AND a.is_published AND char_length(trim(a.instructions))>=20))
    );

  v_checks:=jsonb_build_array(
    jsonb_build_object('key','title','label','Course title','complete',char_length(trim(c.title))>=3,'detail','Use a title with at least 3 characters.','target','details'),
    jsonb_build_object('key','slug','label','Course URL','complete',nullif(trim(COALESCE(c.slug,'')),'') IS NOT NULL,'detail','Save a valid course URL slug.','target','details'),
    jsonb_build_object('key','summary','label','Course summary','complete',char_length(trim(COALESCE(c.short_description,'')))>=20,'detail','Add a summary with at least 20 characters.','target','details'),
    jsonb_build_object('key','description','label','Course description','complete',char_length(trim(COALESCE(c.description,'')))>=40,'detail','Add a description with at least 40 characters.','target','details'),
    jsonb_build_object('key','taxonomy','label','Category, level, and language','complete',nullif(trim(COALESCE(c.category,'')),'') IS NOT NULL AND c.level IN ('beginner','intermediate','advanced','all_levels') AND nullif(trim(COALESCE(c.language,'')),'') IS NOT NULL,'detail','Choose the governed category, level, and language.','target','details'),
    jsonb_build_object('key','cover','label','Managed course cover','complete',EXISTS(SELECT 1 FROM storage.objects o WHERE o.bucket_id='course-covers' AND COALESCE(c.cover_image,c.thumbnail,'') LIKE '%/course-covers/' || o.name),'detail','Upload the cover through the course cover control.','target','details'),
    jsonb_build_object('key','pricing','label','Valid regional pricing','complete',c.price_egp IS NOT NULL AND c.price_usd IS NOT NULL AND c.price_egp>=0 AND c.price_usd>=0 AND ((c.price_egp=0 AND c.price_usd=0) OR (c.price_egp>0 AND c.price_usd>0)),'detail','Set valid EGP and USD prices; free courses must be zero in both.','target','pricing'),
    jsonb_build_object('key','instructor','label','Active approved instructor','complete',c.instructor_id IS NOT NULL AND public.is_approved_instructor(c.instructor_id) AND EXISTS(SELECT 1 FROM public.instructor_public_profiles ip WHERE ip.user_id=c.instructor_id AND ip.is_public),'detail','Assign an approved instructor with an active public profile.','target','details'),
    jsonb_build_object('key','sections','label','Published course section','complete',v_published_sections>0,'detail','Publish at least one non-deleted section.','target','curriculum'),
    jsonb_build_object('key','lessons','label','Published lesson','complete',v_published_lessons>0,'detail','Publish at least one lesson inside a published section.','target','curriculum'),
    jsonb_build_object('key','relationships','label','Curriculum relationships','complete',v_orphans=0,'detail','Move every lesson into a valid section in this course.','target','curriculum'),
    jsonb_build_object('key','ordering','label','Unique curriculum ordering','complete',v_order_conflicts=0,'detail','Reorder duplicate section or lesson positions.','target','curriculum'),
    jsonb_build_object('key','content','label','Lesson content is ready','complete',v_invalid_content=0,'detail','Complete every published lesson and verify all media.','target','curriculum'),
    jsonb_build_object('key','quizzes','label','Published quizzes are valid','complete',v_invalid_quizzes=0,'detail','Every quiz needs a published question with at least two choices and one correct answer.','target','curriculum')
  );
  RETURN jsonb_build_object('policy_version',2,'ready',NOT EXISTS(SELECT 1 FROM jsonb_array_elements(v_checks) x WHERE NOT (x->>'complete')::boolean),'checks',v_checks,
    'review_status',c.review_status,'authoring_status',c.authoring_status,'status',c.status,'submitted_revision_id',c.submitted_revision_id,'approved_revision_id',c.approved_revision_id,
    'reviewer_notes',(SELECT notes FROM public.course_review_events WHERE course_id=c.id AND event_type IN('changes_requested','rejected') ORDER BY created_at DESC LIMIT 1));
END $$;

CREATE OR REPLACE FUNCTION public.submit_course_for_review(p_course_id UUID,p_notes TEXT DEFAULT NULL) RETURNS VOID
LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$
DECLARE c public.courses; readiness JSONB; revision public.course_revisions;
BEGIN
  PERFORM public.lock_course_workflow(p_course_id);
  SELECT * INTO c FROM public.courses WHERE id=p_course_id FOR UPDATE;
  IF c.author_id<>auth.uid() OR NOT public.is_approved_instructor(auth.uid()) THEN RAISE EXCEPTION USING ERRCODE='42501',MESSAGE='Approved course owner required'; END IF;
  IF c.authoring_status<>'draft' OR c.review_status NOT IN('not_submitted','changes_requested','rejected') OR c.status<>'draft' THEN RAISE EXCEPTION USING ERRCODE='22023',MESSAGE='Course cannot be submitted from its current state'; END IF;
  readiness:=public.get_course_readiness(p_course_id);
  IF NOT (readiness->>'ready')::boolean THEN RAISE EXCEPTION USING ERRCODE='23514',MESSAGE='Complete every readiness check before submission',DETAIL=readiness::text; END IF;
  revision:=public.create_course_revision(p_course_id);
  UPDATE public.courses SET authoring_status='in_review',review_status='submitted',submitted_revision_id=revision.id,approved_revision_id=NULL,version=version+1,updated_at=now() WHERE id=p_course_id;
  INSERT INTO public.course_review_events(course_id,actor_id,event_type,notes,revision_id) VALUES(p_course_id,auth.uid(),'submitted',nullif(trim(p_notes),''),revision.id);
END $$;

CREATE OR REPLACE FUNCTION public.admin_decide_course_review(p_course_id UUID,p_decision TEXT,p_notes TEXT) RETURNS VOID
LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$
DECLARE c public.courses; readiness JSONB;
BEGIN
  IF NOT public.is_admin() THEN RAISE EXCEPTION USING ERRCODE='42501',MESSAGE='Admin access required'; END IF;
  IF p_decision NOT IN('approved','changes_requested','rejected') THEN RAISE EXCEPTION USING ERRCODE='22023',MESSAGE='Invalid review decision'; END IF;
  IF char_length(trim(COALESCE(p_notes,'')))<5 THEN RAISE EXCEPTION USING ERRCODE='22023',MESSAGE='A review note of at least 5 characters is required for every decision'; END IF;
  PERFORM public.lock_course_workflow(p_course_id);
  SELECT * INTO c FROM public.courses WHERE id=p_course_id FOR UPDATE;
  IF c.authoring_status<>'in_review' OR c.review_status<>'submitted' OR c.submitted_revision_id IS NULL THEN RAISE EXCEPTION USING ERRCODE='40001',MESSAGE='This course review is no longer actionable'; END IF;
  PERFORM public.assert_course_matches_revision(p_course_id,c.submitted_revision_id);
  IF p_decision='approved' THEN
    readiness:=public.get_course_readiness(p_course_id);
    IF NOT (readiness->>'ready')::boolean THEN RAISE EXCEPTION USING ERRCODE='23514',MESSAGE='Course is no longer ready for approval',DETAIL=readiness::text; END IF;
  END IF;
  UPDATE public.courses SET authoring_status=CASE WHEN p_decision='approved' THEN 'approved' ELSE 'draft' END,review_status=p_decision,
    approved_revision_id=CASE WHEN p_decision='approved' THEN submitted_revision_id ELSE NULL END,version=version+1,updated_at=now() WHERE id=p_course_id;
  INSERT INTO public.course_review_events(course_id,actor_id,event_type,notes,revision_id) VALUES(p_course_id,auth.uid(),p_decision,trim(p_notes),c.submitted_revision_id);
END $$;

CREATE OR REPLACE FUNCTION public.admin_set_course_publication(p_course_id UUID,p_publish BOOLEAN) RETURNS VOID
LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$
DECLARE c public.courses; readiness JSONB;
BEGIN
  IF NOT public.is_admin() THEN RAISE EXCEPTION USING ERRCODE='42501',MESSAGE='Admin access required'; END IF;
  PERFORM public.lock_course_workflow(p_course_id);
  SELECT * INTO c FROM public.courses WHERE id=p_course_id FOR UPDATE;
  IF c.id IS NULL THEN RAISE EXCEPTION USING ERRCODE='P0002',MESSAGE='Course not found'; END IF;
  IF p_publish THEN
    IF c.authoring_status<>'approved' OR c.review_status<>'approved' OR c.approved_revision_id IS NULL THEN RAISE EXCEPTION USING ERRCODE='23514',MESSAGE='An approved course revision is required before publication'; END IF;
    PERFORM public.assert_course_matches_revision(p_course_id,c.approved_revision_id);
    readiness:=public.get_course_readiness(p_course_id);
    IF NOT (readiness->>'ready')::boolean THEN RAISE EXCEPTION USING ERRCODE='23514',MESSAGE='Course is no longer ready for publication',DETAIL=readiness::text; END IF;
  ELSIF c.status<>'published' THEN RETURN;
  END IF;
  UPDATE public.courses SET status=CASE WHEN p_publish THEN 'published' ELSE 'draft' END,published_at=CASE WHEN p_publish THEN COALESCE(published_at,now()) ELSE published_at END,version=version+1,updated_at=now() WHERE id=p_course_id;
  INSERT INTO public.course_review_events(course_id,actor_id,event_type,revision_id) VALUES(p_course_id,auth.uid(),CASE WHEN p_publish THEN 'published' ELSE 'unpublished' END,c.approved_revision_id);
END $$;

REVOKE ALL ON FUNCTION public.lock_course_workflow(UUID), public.lock_course_content_mutation() FROM PUBLIC;
REVOKE ALL ON FUNCTION public.get_course_readiness(UUID), public.submit_course_for_review(UUID,TEXT), public.admin_decide_course_review(UUID,TEXT,TEXT), public.admin_set_course_publication(UUID,BOOLEAN) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.get_course_readiness(UUID), public.submit_course_for_review(UUID,TEXT), public.admin_decide_course_review(UUID,TEXT,TEXT), public.admin_set_course_publication(UUID,BOOLEAN) TO authenticated;
NOTIFY pgrst, 'reload schema';


-- ============================================================================
-- SOURCE: supabase/migrations/20260730030000_instructor_lifecycle_governance.sql
-- ============================================================================
-- Phase 3: governed instructor lifecycle, history, and suspension safety.

CREATE TABLE public.instructor_application_events (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(), application_id UUID NOT NULL REFERENCES public.instructor_applications(id) ON DELETE RESTRICT,
  actor_id UUID NOT NULL REFERENCES public.users(id) ON DELETE RESTRICT, from_status TEXT NULL, to_status TEXT NOT NULL,
  notes TEXT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX instructor_application_events_application_created_idx ON public.instructor_application_events(application_id,created_at DESC);
ALTER TABLE public.instructor_application_events ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Applicants view own instructor history" ON public.instructor_application_events FOR SELECT TO authenticated
  USING(EXISTS(SELECT 1 FROM public.instructor_applications a WHERE a.id=application_id AND a.user_id=auth.uid()));
CREATE POLICY "Admins view instructor history" ON public.instructor_application_events FOR SELECT TO authenticated USING(public.is_admin());

CREATE OR REPLACE FUNCTION public.submit_instructor_application(
  p_professional_name TEXT,p_bio TEXT,p_expertise TEXT[],p_credentials TEXT,p_portfolio_url TEXT
) RETURNS UUID LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$
DECLARE v_id UUID; v_previous TEXT;
BEGIN
  IF auth.uid() IS NULL THEN RAISE EXCEPTION USING ERRCODE='42501',MESSAGE='Authentication required'; END IF;
  SELECT status INTO v_previous FROM public.instructor_applications WHERE user_id=auth.uid() FOR UPDATE;
  IF v_previous IS NOT NULL AND v_previous NOT IN('changes_requested','rejected') THEN RAISE EXCEPTION USING ERRCODE='22023',MESSAGE='Application cannot be submitted from its current state'; END IF;
  INSERT INTO public.instructor_applications(user_id,professional_name,bio,expertise,credentials,portfolio_url,status,submitted_at,updated_at)
  VALUES(auth.uid(),trim(p_professional_name),trim(p_bio),p_expertise,trim(p_credentials),nullif(trim(p_portfolio_url),''),'submitted',now(),now())
  ON CONFLICT(user_id) DO UPDATE SET professional_name=EXCLUDED.professional_name,bio=EXCLUDED.bio,expertise=EXCLUDED.expertise,
    credentials=EXCLUDED.credentials,portfolio_url=EXCLUDED.portfolio_url,status='submitted',reviewer_id=NULL,reviewer_notes=NULL,submitted_at=now(),reviewed_at=NULL,updated_at=now()
  RETURNING id INTO v_id;
  INSERT INTO public.instructor_application_events(application_id,actor_id,from_status,to_status)
  VALUES(v_id,auth.uid(),v_previous,'submitted');
  RETURN v_id;
END $$;

CREATE OR REPLACE FUNCTION public.admin_review_instructor_application(p_application_id UUID,p_decision TEXT,p_notes TEXT)
RETURNS VOID LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$
DECLARE a public.instructor_applications; v_allowed BOOLEAN:=FALSE; v_course RECORD;
BEGIN
  IF NOT public.is_admin() THEN RAISE EXCEPTION USING ERRCODE='42501',MESSAGE='Admin access required'; END IF;
  IF char_length(trim(COALESCE(p_notes,'')))<5 THEN RAISE EXCEPTION USING ERRCODE='22023',MESSAGE='Review notes must contain at least 5 characters'; END IF;
  SELECT * INTO a FROM public.instructor_applications WHERE id=p_application_id FOR UPDATE;
  IF a.id IS NULL THEN RAISE EXCEPTION USING ERRCODE='P0002',MESSAGE='Application not found'; END IF;
  v_allowed:=(a.status='submitted' AND p_decision IN('under_review','approved','changes_requested','rejected')) OR
    (a.status='under_review' AND p_decision IN('approved','changes_requested','rejected')) OR
    (a.status='approved' AND p_decision='suspended') OR
    (a.status='suspended' AND p_decision IN('approved','rejected'));
  IF NOT v_allowed THEN RAISE EXCEPTION USING ERRCODE='22023',MESSAGE='Instructor transition is not allowed from the current state'; END IF;
  UPDATE public.instructor_applications SET status=p_decision,reviewer_id=auth.uid(),reviewer_notes=trim(p_notes),reviewed_at=now(),updated_at=now() WHERE id=p_application_id;
  INSERT INTO public.instructor_application_events(application_id,actor_id,from_status,to_status,notes) VALUES(a.id,auth.uid(),a.status,p_decision,trim(p_notes));
  IF p_decision='approved' THEN
    INSERT INTO public.instructor_public_profiles(user_id,professional_name,bio,expertise,credentials,approved_at,updated_at)
    VALUES(a.user_id,a.professional_name,a.bio,a.expertise,a.credentials,now(),now())
    ON CONFLICT(user_id) DO UPDATE SET professional_name=EXCLUDED.professional_name,bio=EXCLUDED.bio,expertise=EXCLUDED.expertise,credentials=EXCLUDED.credentials,is_public=TRUE,updated_at=now();
    UPDATE public.users SET role='instructor' WHERE id=a.user_id AND role<>'admin';
    UPDATE auth.users SET raw_app_meta_data=COALESCE(raw_app_meta_data,'{}'::jsonb)||'{"role":"instructor"}'::jsonb WHERE id=a.user_id AND COALESCE(raw_app_meta_data->>'role','')<>'admin';
  ELSIF p_decision IN('suspended','rejected') AND a.status IN('approved','suspended') THEN
    UPDATE public.instructor_public_profiles SET is_public=FALSE,updated_at=now() WHERE user_id=a.user_id;
    UPDATE public.users SET role='student' WHERE id=a.user_id AND role<>'admin';
    UPDATE auth.users SET raw_app_meta_data=COALESCE(raw_app_meta_data,'{}'::jsonb)||'{"role":"student"}'::jsonb WHERE id=a.user_id AND COALESCE(raw_app_meta_data->>'role','')<>'admin';
    FOR v_course IN UPDATE public.courses SET status='draft',updated_at=now()
      WHERE status='published' AND (author_id=a.user_id OR instructor_id=a.user_id) RETURNING id,approved_revision_id LOOP
      INSERT INTO public.course_review_events(course_id,actor_id,event_type,notes,revision_id)
      VALUES(v_course.id,auth.uid(),'unpublished','Instructor access was suspended.',v_course.approved_revision_id);
    END LOOP;
  END IF;
END $$;

REVOKE ALL ON FUNCTION public.submit_instructor_application(TEXT,TEXT,TEXT[],TEXT,TEXT), public.admin_review_instructor_application(UUID,TEXT,TEXT) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.submit_instructor_application(TEXT,TEXT,TEXT[],TEXT,TEXT), public.admin_review_instructor_application(UUID,TEXT,TEXT) TO authenticated;
NOTIFY pgrst,'reload schema';


-- ============================================================================
-- SOURCE: supabase/migrations/20260730040000_reviewer_workspace.sql
-- ============================================================================
-- Phase 4: reviewer assignment, structured findings, and scalable review queue.

ALTER TABLE public.courses
  ADD COLUMN review_assignee_id UUID NULL REFERENCES public.users(id) ON DELETE SET NULL,
  ADD COLUMN review_claimed_at TIMESTAMPTZ NULL,
  ADD COLUMN review_due_at TIMESTAMPTZ NULL;
CREATE INDEX courses_review_queue_idx ON public.courses(review_status,review_due_at,updated_at,id) WHERE review_status='submitted';

CREATE TABLE public.course_review_findings (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(), course_id UUID NOT NULL REFERENCES public.courses(id) ON DELETE RESTRICT,
  revision_id UUID NOT NULL REFERENCES public.course_revisions(id) ON DELETE RESTRICT, reviewer_id UUID NOT NULL REFERENCES public.users(id) ON DELETE RESTRICT,
  category TEXT NOT NULL CHECK(category IN('course_details','pricing','instructor','media','curriculum','quiz','assignment','accessibility','seo','other')),
  severity TEXT NOT NULL CHECK(severity IN('warning','blocking')), target_type TEXT NULL, target_id UUID NULL,
  comment TEXT NOT NULL CHECK(char_length(trim(comment))>=5), status TEXT NOT NULL DEFAULT 'open' CHECK(status IN('open','resolved','dismissed')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX course_review_findings_revision_status_idx ON public.course_review_findings(revision_id,status,created_at);
ALTER TABLE public.course_review_findings ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Authors view own review findings" ON public.course_review_findings FOR SELECT TO authenticated
  USING(EXISTS(SELECT 1 FROM public.courses c WHERE c.id=course_id AND c.author_id=auth.uid()));
CREATE POLICY "Admins manage review findings" ON public.course_review_findings FOR ALL TO authenticated USING(public.is_admin()) WITH CHECK(public.is_admin());

CREATE OR REPLACE FUNCTION public.admin_claim_course_review(p_course_id UUID,p_claim BOOLEAN DEFAULT TRUE) RETURNS VOID
LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$
DECLARE c public.courses;
BEGIN
  IF NOT public.is_admin() THEN RAISE EXCEPTION USING ERRCODE='42501',MESSAGE='Admin access required'; END IF;
  PERFORM public.lock_course_workflow(p_course_id);
  SELECT * INTO c FROM public.courses WHERE id=p_course_id FOR UPDATE;
  IF c.review_status<>'submitted' THEN RAISE EXCEPTION USING ERRCODE='22023',MESSAGE='Only submitted courses can be assigned'; END IF;
  IF p_claim AND c.review_assignee_id IS NOT NULL AND c.review_assignee_id<>auth.uid() THEN RAISE EXCEPTION USING ERRCODE='40001',MESSAGE='This review is already assigned to another administrator'; END IF;
  IF NOT p_claim AND c.review_assignee_id<>auth.uid() THEN RAISE EXCEPTION USING ERRCODE='42501',MESSAGE='Only the assigned reviewer can release this review'; END IF;
  UPDATE public.courses SET review_assignee_id=CASE WHEN p_claim THEN auth.uid() ELSE NULL END,
    review_claimed_at=CASE WHEN p_claim THEN now() ELSE NULL END,review_due_at=CASE WHEN p_claim THEN now()+interval '3 days' ELSE NULL END,updated_at=now() WHERE id=p_course_id;
END $$;

CREATE OR REPLACE FUNCTION public.admin_save_course_review_finding(p_course_id UUID,p_category TEXT,p_severity TEXT,p_comment TEXT,p_target_type TEXT DEFAULT NULL,p_target_id UUID DEFAULT NULL)
RETURNS UUID LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$
DECLARE c public.courses; v_id UUID;
BEGIN
  IF NOT public.is_admin() THEN RAISE EXCEPTION USING ERRCODE='42501',MESSAGE='Admin access required'; END IF;
  SELECT * INTO c FROM public.courses WHERE id=p_course_id;
  IF c.review_status<>'submitted' OR c.submitted_revision_id IS NULL THEN RAISE EXCEPTION USING ERRCODE='22023',MESSAGE='Only submitted revisions can receive findings'; END IF;
  IF c.review_assignee_id IS DISTINCT FROM auth.uid() THEN RAISE EXCEPTION USING ERRCODE='42501',MESSAGE='Claim this review before adding findings'; END IF;
  INSERT INTO public.course_review_findings(course_id,revision_id,reviewer_id,category,severity,target_type,target_id,comment)
  VALUES(c.id,c.submitted_revision_id,auth.uid(),p_category,p_severity,nullif(trim(p_target_type),''),p_target_id,trim(p_comment)) RETURNING id INTO v_id;
  RETURN v_id;
END $$;

CREATE OR REPLACE FUNCTION public.admin_set_course_review_finding_status(p_finding_id UUID,p_status TEXT) RETURNS VOID
LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$
BEGIN
  IF NOT public.is_admin() OR p_status NOT IN('open','resolved','dismissed') THEN RAISE EXCEPTION USING ERRCODE='42501',MESSAGE='Admin access required'; END IF;
  UPDATE public.course_review_findings SET status=p_status,updated_at=now() WHERE id=p_finding_id;
  IF NOT FOUND THEN RAISE EXCEPTION USING ERRCODE='P0002',MESSAGE='Review finding not found'; END IF;
END $$;

CREATE OR REPLACE FUNCTION public.admin_get_course_review_workspace(p_course_id UUID) RETURNS JSONB
LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path=public AS $$
DECLARE c public.courses;
BEGIN
  IF NOT public.is_admin() THEN RAISE EXCEPTION USING ERRCODE='42501',MESSAGE='Admin access required'; END IF;
  SELECT * INTO c FROM public.courses WHERE id=p_course_id;
  IF c.id IS NULL THEN RAISE EXCEPTION USING ERRCODE='P0002',MESSAGE='Course not found'; END IF;
  RETURN jsonb_build_object('course',jsonb_build_object('id',c.id,'title',c.title,'review_status',c.review_status,'assignee_id',c.review_assignee_id,'claimed_at',c.review_claimed_at,'due_at',c.review_due_at),
    'revision',(SELECT jsonb_build_object('id',r.id,'number',r.revision_number,'snapshot',r.snapshot,'created_at',r.created_at) FROM public.course_revisions r WHERE r.id=c.submitted_revision_id),
    'readiness',public.get_course_readiness(c.id),
    'findings',COALESCE((SELECT jsonb_agg(to_jsonb(f) ORDER BY f.created_at DESC) FROM public.course_review_findings f WHERE f.revision_id=c.submitted_revision_id),'[]'::jsonb),
    'history',COALESCE((SELECT jsonb_agg(jsonb_build_object('id',e.id,'event_type',e.event_type,'notes',e.notes,'created_at',e.created_at,'actor_name',u.full_name) ORDER BY e.created_at DESC) FROM public.course_review_events e LEFT JOIN public.users u ON u.id=e.actor_id WHERE e.course_id=c.id),'[]'::jsonb));
END $$;

CREATE OR REPLACE FUNCTION public.admin_decide_course_review(p_course_id UUID,p_decision TEXT,p_notes TEXT) RETURNS VOID
LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$
DECLARE c public.courses; readiness JSONB;
BEGIN
  IF NOT public.is_admin() THEN RAISE EXCEPTION USING ERRCODE='42501',MESSAGE='Admin access required'; END IF;
  IF p_decision NOT IN('approved','changes_requested','rejected') OR char_length(trim(COALESCE(p_notes,'')))<5 THEN RAISE EXCEPTION USING ERRCODE='22023',MESSAGE='A valid decision and actionable review note are required'; END IF;
  PERFORM public.lock_course_workflow(p_course_id);
  SELECT * INTO c FROM public.courses WHERE id=p_course_id FOR UPDATE;
  IF c.authoring_status<>'in_review' OR c.review_status<>'submitted' OR c.submitted_revision_id IS NULL THEN RAISE EXCEPTION USING ERRCODE='40001',MESSAGE='This course review is no longer actionable'; END IF;
  IF c.review_assignee_id IS DISTINCT FROM auth.uid() THEN RAISE EXCEPTION USING ERRCODE='42501',MESSAGE='Claim this review before making a decision'; END IF;
  PERFORM public.assert_course_matches_revision(p_course_id,c.submitted_revision_id);
  IF p_decision='approved' THEN
    IF EXISTS(SELECT 1 FROM public.course_review_findings f WHERE f.revision_id=c.submitted_revision_id AND f.status='open' AND f.severity='blocking') THEN RAISE EXCEPTION USING ERRCODE='23514',MESSAGE='Resolve every blocking finding before approval'; END IF;
    readiness:=public.get_course_readiness(p_course_id);
    IF NOT (readiness->>'ready')::boolean THEN RAISE EXCEPTION USING ERRCODE='23514',MESSAGE='Course is no longer ready for approval',DETAIL=readiness::text; END IF;
  END IF;
  UPDATE public.courses SET authoring_status=CASE WHEN p_decision='approved' THEN 'approved' ELSE 'draft' END,review_status=p_decision,
    approved_revision_id=CASE WHEN p_decision='approved' THEN submitted_revision_id ELSE NULL END,review_assignee_id=NULL,review_claimed_at=NULL,review_due_at=NULL,version=version+1,updated_at=now() WHERE id=p_course_id;
  INSERT INTO public.course_review_events(course_id,actor_id,event_type,notes,revision_id) VALUES(p_course_id,auth.uid(),p_decision,trim(p_notes),c.submitted_revision_id);
END $$;

DROP FUNCTION IF EXISTS public.admin_list_course_reviews();
CREATE FUNCTION public.admin_list_course_reviews(p_query TEXT DEFAULT '',p_limit INTEGER DEFAULT 25,p_cursor TIMESTAMPTZ DEFAULT NULL)
RETURNS TABLE(course_id UUID,title TEXT,author_name TEXT,submitted_at TIMESTAMPTZ,assignee_id UUID,assignee_name TEXT,due_at TIMESTAMPTZ,open_findings BIGINT)
LANGUAGE sql STABLE SECURITY DEFINER SET search_path=public AS $$
  SELECT c.id,c.title,u.full_name,e.submitted_at,c.review_assignee_id,reviewer.full_name,c.review_due_at,
    (SELECT count(*) FROM public.course_review_findings f WHERE f.revision_id=c.submitted_revision_id AND f.status='open')
  FROM public.courses c LEFT JOIN public.users u ON u.id=c.author_id LEFT JOIN public.users reviewer ON reviewer.id=c.review_assignee_id
  CROSS JOIN LATERAL(SELECT max(created_at) submitted_at FROM public.course_review_events WHERE course_id=c.id AND event_type='submitted') e
  WHERE public.is_admin() AND c.review_status='submitted' AND (trim(p_query)='' OR c.title ILIKE '%'||trim(p_query)||'%' OR u.full_name ILIKE '%'||trim(p_query)||'%')
    AND (p_cursor IS NULL OR e.submitted_at<p_cursor)
  ORDER BY e.submitted_at DESC,c.id LIMIT LEAST(GREATEST(p_limit,1),100);
$$;

REVOKE ALL ON FUNCTION public.admin_claim_course_review(UUID,BOOLEAN),public.admin_save_course_review_finding(UUID,TEXT,TEXT,TEXT,TEXT,UUID),public.admin_set_course_review_finding_status(UUID,TEXT),public.admin_get_course_review_workspace(UUID),public.admin_list_course_reviews(TEXT,INTEGER,TIMESTAMPTZ),public.admin_decide_course_review(UUID,TEXT,TEXT) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.admin_claim_course_review(UUID,BOOLEAN),public.admin_save_course_review_finding(UUID,TEXT,TEXT,TEXT,TEXT,UUID),public.admin_set_course_review_finding_status(UUID,TEXT),public.admin_get_course_review_workspace(UUID),public.admin_list_course_reviews(TEXT,INTEGER,TIMESTAMPTZ),public.admin_decide_course_review(UUID,TEXT,TEXT) TO authenticated;
NOTIFY pgrst,'reload schema';


-- ============================================================================
-- SOURCE: supabase/migrations/20260730050000_course_cover_optimization.sql
-- ============================================================================
-- Phase 5: enforce the optimized course-cover storage contract.

UPDATE storage.buckets SET file_size_limit=716800,allowed_mime_types=ARRAY['image/webp'] WHERE id='course-covers';
DROP POLICY IF EXISTS "Authors delete own course covers" ON storage.objects;
CREATE POLICY "Authors delete own course covers" ON storage.objects FOR DELETE TO authenticated
USING(bucket_id='course-covers' AND (storage.foldername(name))[1]=auth.uid()::text AND (public.is_admin() OR public.is_approved_instructor(auth.uid())));

CREATE OR REPLACE FUNCTION public.cleanup_replaced_course_cover() RETURNS TRIGGER
LANGUAGE plpgsql SECURITY DEFINER SET search_path=public,storage AS $$
DECLARE v_url TEXT;v_name TEXT;
BEGIN
  FOR v_url IN SELECT DISTINCT value FROM unnest(ARRAY[OLD.cover_image,OLD.thumbnail]) value WHERE value IS NOT NULL LOOP
    IF (TG_OP='UPDATE' AND v_url IN (COALESCE(NEW.cover_image,''),COALESCE(NEW.thumbnail,''))) THEN CONTINUE; END IF;
    v_name:=split_part(v_url,'/course-covers/',2);
    IF v_name<>'' AND NOT EXISTS(SELECT 1 FROM public.courses c WHERE c.id<>OLD.id AND v_url IN (c.cover_image,c.thumbnail)) THEN
      DELETE FROM storage.objects WHERE bucket_id='course-covers' AND name=v_name;
    END IF;
  END LOOP;
  IF TG_OP='DELETE' THEN RETURN OLD; END IF;
  RETURN NEW;
END $$;
DROP TRIGGER IF EXISTS trg_courses_cleanup_cover ON public.courses;
CREATE TRIGGER trg_courses_cleanup_cover AFTER UPDATE OF cover_image,thumbnail OR DELETE ON public.courses FOR EACH ROW EXECUTE FUNCTION public.cleanup_replaced_course_cover();
REVOKE ALL ON FUNCTION public.cleanup_replaced_course_cover() FROM PUBLIC;
NOTIFY pgrst,'reload schema';


-- ============================================================================
-- SOURCE: supabase/migrations/20260730060000_workflow_operations.sql
-- ============================================================================
-- Phase 8: production workflow health, reconciliation, and release evidence.

CREATE TABLE IF NOT EXISTS public.platform_feature_releases(
  release_key TEXT PRIMARY KEY,applied_at TIMESTAMPTZ NOT NULL DEFAULT now(),applied_by UUID NULL REFERENCES public.users(id) ON DELETE SET NULL,details JSONB NOT NULL DEFAULT '{}'::jsonb
);
ALTER TABLE public.platform_feature_releases ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Admins view feature releases" ON public.platform_feature_releases;
CREATE POLICY "Admins view feature releases" ON public.platform_feature_releases FOR SELECT TO authenticated USING(public.is_admin());

CREATE OR REPLACE FUNCTION public.admin_get_workflow_health() RETURNS JSONB
LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path=public,storage AS $$
BEGIN
  IF NOT public.is_admin() THEN RAISE EXCEPTION USING ERRCODE='42501',MESSAGE='Admin access required'; END IF;
  RETURN jsonb_build_object(
    'checked_at',now(),
    'published_without_approved_revision',(SELECT count(*) FROM public.courses WHERE status='published' AND (review_status<>'approved' OR approved_revision_id IS NULL)),
    'submitted_without_revision',(SELECT count(*) FROM public.courses WHERE review_status='submitted' AND submitted_revision_id IS NULL),
    'overdue_unfinished_reviews',(SELECT count(*) FROM public.courses WHERE review_status='submitted' AND review_due_at<now()),
    'open_blocking_findings',(SELECT count(*) FROM public.course_review_findings WHERE status='open' AND severity='blocking'),
    'approved_instructor_role_drift',(SELECT count(*) FROM public.instructor_applications a JOIN public.users u ON u.id=a.user_id WHERE a.status='approved' AND u.role NOT IN('instructor','admin')),
    'inactive_instructor_public_profiles',(SELECT count(*) FROM public.instructor_public_profiles p LEFT JOIN public.instructor_applications a ON a.user_id=p.user_id AND a.status='approved' WHERE p.is_public AND a.id IS NULL),
    'missing_managed_covers',(SELECT count(*) FROM public.courses c WHERE c.status='published' AND NOT EXISTS(SELECT 1 FROM storage.objects o WHERE o.bucket_id='course-covers' AND COALESCE(c.cover_image,c.thumbnail,'') LIKE '%/course-covers/'||o.name))
  );
END $$;

CREATE OR REPLACE FUNCTION public.admin_get_workflow_metrics(p_since TIMESTAMPTZ DEFAULT now()-interval '30 days') RETURNS JSONB
LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path=public AS $$
BEGIN
  IF NOT public.is_admin() THEN RAISE EXCEPTION USING ERRCODE='42501',MESSAGE='Admin access required'; END IF;
  RETURN jsonb_build_object('since',p_since,'course_submissions',(SELECT count(*) FROM public.course_review_events WHERE event_type='submitted' AND created_at>=p_since),
    'course_approvals',(SELECT count(*) FROM public.course_review_events WHERE event_type='approved' AND created_at>=p_since),
    'changes_requested',(SELECT count(*) FROM public.course_review_events WHERE event_type='changes_requested' AND created_at>=p_since),
    'publications',(SELECT count(*) FROM public.course_review_events WHERE event_type='published' AND created_at>=p_since),
    'instructor_approvals',(SELECT count(*) FROM public.instructor_application_events WHERE to_status='approved' AND created_at>=p_since),
    'instructor_suspensions',(SELECT count(*) FROM public.instructor_application_events WHERE to_status='suspended' AND created_at>=p_since));
END $$;

REVOKE ALL ON FUNCTION public.admin_get_workflow_health(),public.admin_get_workflow_metrics(TIMESTAMPTZ) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.admin_get_workflow_health(),public.admin_get_workflow_metrics(TIMESTAMPTZ) TO authenticated;
INSERT INTO public.platform_feature_releases(release_key,applied_by,details) VALUES('course-review-production-v1',auth.uid(),jsonb_build_object('phases',8,'migration','20260730060000')) ON CONFLICT(release_key) DO NOTHING;
NOTIFY pgrst,'reload schema';


-- ============================================================================
-- SOURCE: supabase/migrations/20260730070000_authoring_data_integrity_foundation.sql
-- ============================================================================
-- Phase 1: production preflight, duration compatibility, and canonical curriculum ordering.

DO $$ DECLARE v_name TEXT; BEGIN
  FOREACH v_name IN ARRAY ARRAY['courses','course_sections','lessons','course_revisions','course_review_events','course_review_findings','quizzes','questions','question_options','assignment_definitions','assignment_submissions'] LOOP
    IF to_regclass('public.'||v_name) IS NULL THEN RAISE EXCEPTION 'Authoring integrity preflight failed: public.% is missing',v_name; END IF;
  END LOOP;
  IF NOT EXISTS(SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='lessons' AND column_name='video_duration_seconds' AND data_type='integer') THEN RAISE EXCEPTION 'Authoring integrity preflight failed: lessons.video_duration_seconds must be INTEGER'; END IF;
  IF NOT EXISTS(SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='lessons' AND column_name='estimated_minutes' AND data_type='integer') THEN RAISE EXCEPTION 'Authoring integrity preflight failed: lessons.estimated_minutes must be INTEGER'; END IF;
  IF to_regprocedure('public.author_save_quiz(uuid,jsonb)') IS NULL OR to_regprocedure('public.author_save_assignment(uuid,jsonb)') IS NULL THEN RAISE EXCEPTION 'Authoring integrity preflight failed: quiz and assignment author RPCs are required'; END IF;
END $$;

COMMENT ON COLUMN public.lessons.video_duration_seconds IS 'Canonical video duration in seconds. Never store display labels here.';
COMMENT ON COLUMN public.lessons.estimated_minutes IS 'Canonical estimated whole minutes, derived from media metadata.';
COMMENT ON COLUMN public.lessons.duration IS 'Deprecated compatibility column. New writes use video_duration_seconds and estimated_minutes.';

CREATE OR REPLACE FUNCTION public.admin_set_lesson_video_metadata(p_lesson_id UUID,p_video_url TEXT,p_provider TEXT,p_duration_seconds INTEGER,p_status TEXT)
RETURNS BIGINT LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$
DECLARE v_course_id UUID;
BEGIN
  SELECT course_id INTO v_course_id FROM public.lessons WHERE id=p_lesson_id AND deleted_at IS NULL AND public.can_author_course(course_id);
  IF v_course_id IS NULL THEN RAISE EXCEPTION USING ERRCODE='42501',MESSAGE='Course author access required'; END IF;
  IF p_status NOT IN('pending','ready','unavailable','failed') THEN RAISE EXCEPTION USING ERRCODE='22023',MESSAGE='Invalid metadata status'; END IF;
  IF p_status='ready' AND (p_duration_seconds IS NULL OR p_duration_seconds<=0) THEN RAISE EXCEPTION USING ERRCODE='22023',MESSAGE='Ready video metadata requires duration'; END IF;
  PERFORM public.lock_course_workflow(v_course_id);
  UPDATE public.lessons SET video_url=nullif(trim(p_video_url),''),video_provider=nullif(trim(p_provider),''),video_duration_seconds=CASE WHEN p_status='ready' THEN p_duration_seconds ELSE NULL END,estimated_minutes=CASE WHEN p_status='ready' THEN ceil(p_duration_seconds/60.0)::INTEGER ELSE 0 END,video_metadata_status=p_status,video_metadata_updated_at=now(),updated_at=now(),version=version+1
  WHERE id=p_lesson_id AND course_id=v_course_id AND content_type='video' AND deleted_at IS NULL;
  IF NOT FOUND THEN RAISE EXCEPTION USING ERRCODE='P0002',MESSAGE='Video lesson not found'; END IF;
  RETURN public.recalculate_course_video_duration(v_course_id);
END $$;

WITH ranked AS(SELECT id,row_number() OVER(PARTITION BY course_id ORDER BY order_index,id)-1 canonical_order FROM public.course_sections WHERE deleted_at IS NULL)
UPDATE public.course_sections s SET order_index=r.canonical_order,updated_at=now() FROM ranked r WHERE s.id=r.id AND s.order_index IS DISTINCT FROM r.canonical_order;
WITH ranked AS(SELECT id,row_number() OVER(PARTITION BY course_id,section_id ORDER BY order_index,id)-1 canonical_order FROM public.lessons WHERE deleted_at IS NULL AND section_id IS NOT NULL)
UPDATE public.lessons l SET order_index=r.canonical_order,updated_at=now(),version=version+1 FROM ranked r WHERE l.id=r.id AND l.order_index IS DISTINCT FROM r.canonical_order;

CREATE OR REPLACE FUNCTION public.admin_reorder_course_sections(p_course_id UUID,p_section_ids UUID[]) RETURNS VOID
LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$
DECLARE v_expected INTEGER;v_supplied INTEGER;
BEGIN
  IF NOT public.can_author_course(p_course_id) THEN RAISE EXCEPTION USING ERRCODE='42501',MESSAGE='Course author access required'; END IF;
  PERFORM public.lock_course_workflow(p_course_id);
  SELECT count(*) INTO v_expected FROM public.course_sections WHERE course_id=p_course_id AND deleted_at IS NULL;v_supplied:=COALESCE(cardinality(p_section_ids),0);
  IF v_supplied<>v_expected OR (SELECT count(DISTINCT id) FROM unnest(COALESCE(p_section_ids,ARRAY[]::UUID[])) id)<>v_supplied OR (SELECT count(*) FROM public.course_sections WHERE course_id=p_course_id AND deleted_at IS NULL AND id=ANY(COALESCE(p_section_ids,ARRAY[]::UUID[])))<>v_expected THEN RAISE EXCEPTION USING ERRCODE='23514',MESSAGE='Section reorder must include every active course section exactly once'; END IF;
  UPDATE public.course_sections s SET order_index=u.ordinality-1,updated_at=now() FROM unnest(COALESCE(p_section_ids,ARRAY[]::UUID[])) WITH ORDINALITY u(id,ordinality) WHERE s.id=u.id AND s.course_id=p_course_id;
END $$;

CREATE OR REPLACE FUNCTION public.admin_reorder_section_lessons(p_course_id UUID,p_section_id UUID,p_lesson_ids UUID[]) RETURNS VOID
LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$
DECLARE v_expected INTEGER;v_supplied INTEGER;
BEGIN
  IF NOT public.can_author_course(p_course_id) THEN RAISE EXCEPTION USING ERRCODE='42501',MESSAGE='Course author access required'; END IF;
  PERFORM public.lock_course_workflow(p_course_id);
  IF NOT EXISTS(SELECT 1 FROM public.course_sections WHERE id=p_section_id AND course_id=p_course_id AND deleted_at IS NULL) THEN RAISE EXCEPTION USING ERRCODE='23514',MESSAGE='Section does not belong to course'; END IF;
  SELECT count(*) INTO v_expected FROM public.lessons WHERE course_id=p_course_id AND section_id=p_section_id AND deleted_at IS NULL;v_supplied:=COALESCE(cardinality(p_lesson_ids),0);
  IF v_supplied<>v_expected OR (SELECT count(DISTINCT id) FROM unnest(COALESCE(p_lesson_ids,ARRAY[]::UUID[])) id)<>v_supplied OR (SELECT count(*) FROM public.lessons WHERE course_id=p_course_id AND section_id=p_section_id AND deleted_at IS NULL AND id=ANY(COALESCE(p_lesson_ids,ARRAY[]::UUID[])))<>v_expected THEN RAISE EXCEPTION USING ERRCODE='23514',MESSAGE='Lesson reorder must include every active section lesson exactly once'; END IF;
  UPDATE public.lessons l SET order_index=u.ordinality-1,updated_at=now(),version=version+1 FROM unnest(COALESCE(p_lesson_ids,ARRAY[]::UUID[])) WITH ORDINALITY u(id,ordinality) WHERE l.id=u.id AND l.course_id=p_course_id AND l.section_id=p_section_id;
END $$;

REVOKE ALL ON FUNCTION public.admin_set_lesson_video_metadata(UUID,TEXT,TEXT,INTEGER,TEXT),public.admin_reorder_course_sections(UUID,UUID[]),public.admin_reorder_section_lessons(UUID,UUID,UUID[]) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.admin_set_lesson_video_metadata(UUID,TEXT,TEXT,INTEGER,TEXT),public.admin_reorder_course_sections(UUID,UUID[]),public.admin_reorder_section_lessons(UUID,UUID,UUID[]) TO authenticated;
INSERT INTO public.platform_feature_releases(release_key,applied_by,details) VALUES('authoring-data-integrity-v1',auth.uid(),jsonb_build_object('migration','20260730070000','duration_source','numeric_metadata','lesson_types',jsonb_build_array('video','pdf','external_link','quiz','assignment'))) ON CONFLICT(release_key) DO NOTHING;
NOTIFY pgrst,'reload schema';


-- ============================================================================
-- SOURCE: supabase/migrations/20260730080000_review_auto_publication.sql
-- ============================================================================
-- Phase 2: admin finalization and atomic approval-to-publication workflow.

CREATE OR REPLACE FUNCTION public.admin_finalize_course_for_review(p_course_id UUID,p_notes TEXT DEFAULT NULL)
RETURNS UUID LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$
DECLARE c public.courses;readiness JSONB;revision public.course_revisions;
BEGIN
 IF NOT public.is_admin() THEN RAISE EXCEPTION USING ERRCODE='42501',MESSAGE='Admin access required'; END IF;
 PERFORM public.lock_course_workflow(p_course_id);SELECT * INTO c FROM public.courses WHERE id=p_course_id FOR UPDATE;
 IF c.id IS NULL THEN RAISE EXCEPTION USING ERRCODE='P0002',MESSAGE='Course not found'; END IF;
 IF c.author_id IS NOT NULL AND c.author_id<>auth.uid() THEN RAISE EXCEPTION USING ERRCODE='42501',MESSAGE='Only an administrator-owned draft can use admin finalization'; END IF;
 IF c.authoring_status<>'draft' OR c.review_status NOT IN('not_submitted','changes_requested','rejected') OR c.status<>'draft' THEN RAISE EXCEPTION USING ERRCODE='22023',MESSAGE='Course cannot be finalized from its current state'; END IF;
 readiness:=public.get_course_readiness(p_course_id);IF NOT(readiness->>'ready')::BOOLEAN THEN RAISE EXCEPTION USING ERRCODE='23514',MESSAGE='Complete every readiness check before finalizing',DETAIL=readiness::TEXT;END IF;
 revision:=public.create_course_revision(p_course_id);
 UPDATE public.courses SET authoring_status='in_review',review_status='submitted',submitted_revision_id=revision.id,approved_revision_id=NULL,review_assignee_id=NULL,review_claimed_at=NULL,review_due_at=NULL,version=version+1,updated_at=now() WHERE id=p_course_id;
 INSERT INTO public.course_review_events(course_id,actor_id,event_type,notes,revision_id)VALUES(p_course_id,auth.uid(),'submitted',COALESCE(nullif(trim(p_notes),''),'Finalized by administrator'),revision.id);
 RETURN revision.id;
END $$;

CREATE OR REPLACE FUNCTION public.admin_decide_course_review(p_course_id UUID,p_decision TEXT,p_notes TEXT) RETURNS VOID
LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$
DECLARE c public.courses;readiness JSONB;
BEGIN
 IF NOT public.is_admin() THEN RAISE EXCEPTION USING ERRCODE='42501',MESSAGE='Admin access required'; END IF;
 IF p_decision NOT IN('approved','changes_requested','rejected') OR char_length(trim(COALESCE(p_notes,'')))<5 THEN RAISE EXCEPTION USING ERRCODE='22023',MESSAGE='A valid decision and actionable review note are required'; END IF;
 PERFORM public.lock_course_workflow(p_course_id);SELECT * INTO c FROM public.courses WHERE id=p_course_id FOR UPDATE;
 IF c.authoring_status<>'in_review' OR c.review_status<>'submitted' OR c.submitted_revision_id IS NULL THEN RAISE EXCEPTION USING ERRCODE='40001',MESSAGE='This course review is no longer actionable'; END IF;
 IF c.review_assignee_id IS DISTINCT FROM auth.uid() THEN RAISE EXCEPTION USING ERRCODE='42501',MESSAGE='Claim this review before making a decision'; END IF;
 PERFORM public.assert_course_matches_revision(p_course_id,c.submitted_revision_id);
 IF p_decision='approved' THEN
  IF EXISTS(SELECT 1 FROM public.course_review_findings WHERE revision_id=c.submitted_revision_id AND status='open' AND severity='blocking') THEN RAISE EXCEPTION USING ERRCODE='23514',MESSAGE='Resolve every blocking finding before approval'; END IF;
  readiness:=public.get_course_readiness(p_course_id);IF NOT(readiness->>'ready')::BOOLEAN THEN RAISE EXCEPTION USING ERRCODE='23514',MESSAGE='Course is no longer ready for approval',DETAIL=readiness::TEXT;END IF;
 END IF;
 UPDATE public.courses SET authoring_status=CASE WHEN p_decision='approved' THEN 'approved' ELSE 'draft' END,review_status=p_decision,approved_revision_id=CASE WHEN p_decision='approved' THEN submitted_revision_id ELSE NULL END,status=CASE WHEN p_decision='approved' THEN 'published' ELSE 'draft' END,published_at=CASE WHEN p_decision='approved' THEN COALESCE(published_at,now()) ELSE published_at END,review_assignee_id=NULL,review_claimed_at=NULL,review_due_at=NULL,version=version+1,updated_at=now() WHERE id=p_course_id;
 INSERT INTO public.course_review_events(course_id,actor_id,event_type,notes,revision_id)VALUES(p_course_id,auth.uid(),p_decision,trim(p_notes),c.submitted_revision_id);
 IF p_decision='approved' THEN INSERT INTO public.course_review_events(course_id,actor_id,event_type,notes,revision_id)VALUES(p_course_id,auth.uid(),'published','Published automatically after approval',c.submitted_revision_id);END IF;
END $$;
REVOKE ALL ON FUNCTION public.admin_finalize_course_for_review(UUID,TEXT),public.admin_decide_course_review(UUID,TEXT,TEXT) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.admin_finalize_course_for_review(UUID,TEXT),public.admin_decide_course_review(UUID,TEXT,TEXT) TO authenticated;
INSERT INTO public.platform_feature_releases(release_key,applied_by,details)VALUES('review-auto-publication-v1',auth.uid(),jsonb_build_object('migration','20260730080000','admin_finalize',true,'approval_auto_publishes',true))ON CONFLICT(release_key)DO NOTHING;
NOTIFY pgrst,'reload schema';COMMIT;


-- ============================================================================
-- SOURCE: supabase/migrations/20260730090000_english_and_course_seo.sql
-- ============================================================================

ALTER TABLE public.courses ALTER COLUMN language SET DEFAULT 'English';
UPDATE public.courses SET language='English' WHERE language IS NULL OR btrim(language)='';

CREATE OR REPLACE FUNCTION public.generate_course_seo_title(p_title text)
RETURNS text LANGUAGE sql IMMUTABLE AS $$
  SELECT left(coalesce(nullif(btrim(regexp_replace(p_title, '<[^>]*>', ' ', 'g')), ''), 'Professional online course') || ' | Tutiba', 60)
$$;

CREATE OR REPLACE FUNCTION public.generate_course_seo_description(p_short_description text, p_description text, p_category text)
RETURNS text LANGUAGE sql IMMUTABLE AS $$
  SELECT left(regexp_replace(coalesce(nullif(btrim(p_short_description), ''), nullif(btrim(p_description), ''), 'Build practical, evidence-based skills with this ' || coalesce(nullif(btrim(p_category), ''), 'professional') || ' online course from Tutiba.'), '<[^>]*>', ' ', 'g'), 160)
$$;

CREATE OR REPLACE FUNCTION public.apply_course_seo_defaults()
RETURNS trigger LANGUAGE plpgsql SET search_path=public AS $$
BEGIN
  IF nullif(btrim(NEW.seo_title), '') IS NULL THEN NEW.seo_title := public.generate_course_seo_title(NEW.title); END IF;
  IF nullif(btrim(NEW.seo_description), '') IS NULL THEN NEW.seo_description := public.generate_course_seo_description(NEW.short_description, NEW.description, NEW.category); END IF;
  RETURN NEW;
END $$;

DROP TRIGGER IF EXISTS trg_courses_seo_defaults ON public.courses;
CREATE TRIGGER trg_courses_seo_defaults BEFORE INSERT OR UPDATE OF title, short_description, description, category, seo_title, seo_description ON public.courses FOR EACH ROW EXECUTE FUNCTION public.apply_course_seo_defaults();

UPDATE public.courses SET seo_title=seo_title, seo_description=seo_description WHERE nullif(btrim(seo_title),'') IS NULL OR nullif(btrim(seo_description),'') IS NULL;

INSERT INTO public.platform_feature_releases(release_key, applied_by, details)
VALUES ('english-pricing-seo-v1', auth.uid(), jsonb_build_object('migration','20260730090000','interface_language','English','unknown_country_currency','USD','seo_defaults',true))
ON CONFLICT (release_key) DO NOTHING;


-- Final postflight: aborts with a precise error if a required object is absent.
DO $$ BEGIN
 IF to_regclass('public.course_revisions') IS NULL OR to_regclass('public.course_review_findings') IS NULL OR to_regclass('public.instructor_application_events') IS NULL THEN RAISE EXCEPTION 'Feature rollout incomplete: required tables are missing'; END IF;
 IF NOT EXISTS(SELECT 1 FROM storage.buckets WHERE id='course-covers' AND file_size_limit=716800 AND allowed_mime_types=ARRAY['image/webp']) THEN RAISE EXCEPTION 'Feature rollout incomplete: course-cover storage contract is missing'; END IF;
 IF NOT EXISTS(SELECT 1 FROM public.platform_feature_releases WHERE release_key='course-review-production-v1') OR NOT EXISTS(SELECT 1 FROM public.platform_feature_releases WHERE release_key='authoring-data-integrity-v1') OR NOT EXISTS(SELECT 1 FROM public.platform_feature_releases WHERE release_key='review-auto-publication-v1') OR NOT EXISTS(SELECT 1 FROM public.platform_feature_releases WHERE release_key='english-pricing-seo-v1') THEN RAISE EXCEPTION 'Feature rollout incomplete: release evidence is missing'; END IF;
END $$;
COMMIT;
SELECT 'COURSE AUTHORING DATABASE DEPLOYMENT COMPLETE' AS deployment_status;
