import { FormEvent, useCallback, useEffect, useState, type ReactElement } from 'react';
import { CheckCircle, GraduationCap, Loader2, MailPlus, PauseCircle, RotateCcw, XCircle } from 'lucide-react';
import { AdminSidebar } from '../../components/admin/AdminSidebar';
import { ConfirmDialog } from '../../components/admin/ConfirmDialog';
import { supabase } from '../../lib/supabase';
import { PageContainer } from '../../components/layout/PageContainer';

type Decision = 'under_review' | 'approved' | 'changes_requested' | 'rejected' | 'suspended';
interface ApplicationRow { id: string; professional_name: string; status: string; bio: string; credentials: string; expertise: string[]; applicant?: { email?: string } }

export function AdminInstructorApplications() {
  const [sidebar,setSidebar]=useState(false); const [rows,setRows]=useState<ApplicationRow[]>([]); const [loading,setLoading]=useState(true);
  const [pending,setPending]=useState<{row:ApplicationRow;decision:Decision}|null>(null); const [notes,setNotes]=useState(''); const [saving,setSaving]=useState(false); const [message,setMessage]=useState('');
  const [inviteEmail,setInviteEmail]=useState(''); const [inviting,setInviting]=useState(false);
  const load=useCallback(async()=>{setLoading(true);const{data,error}=await supabase.rpc('admin_list_instructor_applications');setRows(Array.isArray(data)?data:[]);if(error)setMessage(`Unable to load instructor applications (${error.code||'request_failed'}).`);setLoading(false);},[]);
  useEffect(()=>{void load();},[load]);
  const invite=async(event:FormEvent)=>{event.preventDefault();setInviting(true);setMessage('');const{data}=await supabase.auth.getSession();try{const response=await fetch('/api/instructors/invite',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${data.session?.access_token||''}`},body:JSON.stringify({email:inviteEmail})});const payload=await response.json() as {message?:string;error?:string};if(!response.ok)throw new Error(payload.error||'The invitation could not be sent.');setMessage(payload.message||'Instructor invitation sent.');setInviteEmail('');}catch(error){setMessage(error instanceof Error?error.message:'The invitation could not be sent.');}finally{setInviting(false);}};
  const decide=async()=>{if(!pending)return;if(notes.trim().length<5){setMessage('Add review notes of at least 5 characters.');return;}setSaving(true);const{error}=await supabase.rpc('admin_review_instructor_application',{p_application_id:pending.row.id,p_decision:pending.decision,p_notes:notes.trim()});setSaving(false);if(error){setMessage(error.message);return;}setMessage(`Application ${pending.decision.replace('_',' ')}.`);setPending(null);setNotes('');await load();};
  const actions=(row:ApplicationRow)=>{
    if(row.status==='submitted')return <><Action label="Start review" icon={<RotateCcw/>} onClick={()=>setPending({row,decision:'under_review'})}/><Action label="Approve" primary icon={<CheckCircle/>} onClick={()=>setPending({row,decision:'approved'})}/><Action label="Request changes" danger icon={<XCircle/>} onClick={()=>setPending({row,decision:'changes_requested'})}/></>;
    if(row.status==='under_review')return <><Action label="Approve" primary icon={<CheckCircle/>} onClick={()=>setPending({row,decision:'approved'})}/><Action label="Request changes" danger icon={<XCircle/>} onClick={()=>setPending({row,decision:'changes_requested'})}/><Action label="Reject" danger icon={<XCircle/>} onClick={()=>setPending({row,decision:'rejected'})}/></>;
    if(row.status==='approved')return <Action label="Suspend access" danger icon={<PauseCircle/>} onClick={()=>setPending({row,decision:'suspended'})}/>;
    if(row.status==='suspended')return <Action label="Restore access" primary icon={<CheckCircle/>} onClick={()=>setPending({row,decision:'approved'})}/>;
    return null;
  };
  return <div className="min-h-screen bg-primary-50"><AdminSidebar isOpen={sidebar} setIsOpen={setSidebar}/><main className="pb-24 pt-20 lg:pl-72 lg:pt-8"><PageContainer><header className="mb-8"><p className="font-bold text-amber-700">Quality review</p><h1 className="text-3xl font-bold text-primary-900">Instructor access</h1><p className="mt-2 text-primary-600">Invite instructors, review applications, and suspend or restore authoring access.</p></header>
  <form onSubmit={invite} className="mb-7 flex flex-col gap-3 rounded-2xl border bg-white p-5 sm:flex-row sm:items-end"><label className="flex-1 text-sm font-bold">Invite instructor by email<input type="email" required value={inviteEmail} onChange={event=>setInviteEmail(event.target.value)} placeholder="instructor@example.com" className="mt-2 min-h-11 w-full rounded-xl border px-3 font-normal"/></label><button disabled={inviting} className="inline-flex min-h-11 items-center justify-center gap-2 rounded-xl bg-primary-900 px-5 font-bold text-white disabled:opacity-50">{inviting?<Loader2 className="h-4 w-4 animate-spin"/>:<MailPlus className="h-4 w-4"/>}Send invitation</button></form>
  {message&&<p role="status" className="mb-5 rounded-xl border bg-white p-4">{message}</p>}{loading?<Loader2 className="mx-auto h-8 w-8 animate-spin"/>:rows.length===0?<div className="rounded-2xl border border-dashed bg-white p-12 text-center"><GraduationCap className="mx-auto mb-3 h-10 w-10 text-primary-300"/><p className="font-bold">No instructor applications</p></div>:<div className="space-y-4">{rows.map(row=><article key={row.id} className="rounded-2xl border bg-white p-5 shadow-sm"><div className="flex flex-col gap-4 md:flex-row md:justify-between"><div><div className="flex flex-wrap items-center gap-2"><h2 className="text-xl font-bold">{row.professional_name}</h2><span className="rounded-full bg-primary-100 px-3 py-1 text-xs font-bold">{row.status.replace('_',' ')}</span></div><p className="mt-1 text-sm text-primary-500">{row.applicant?.email}</p><p className="mt-4 max-w-3xl">{row.bio}</p><p className="mt-3 text-sm"><strong>Credentials:</strong> {row.credentials}</p><div className="mt-3 flex flex-wrap gap-2">{(row.expertise||[]).map(item=><span key={item} className="rounded-full bg-amber-50 px-3 py-1 text-xs font-bold text-amber-800">{item}</span>)}</div></div><div className="flex flex-wrap gap-2">{actions(row)}</div></div></article>)}</div>}</PageContainer></main>
  <ConfirmDialog open={Boolean(pending)} title={pending?`${pending.decision.replace('_',' ')} instructor?`:'Confirm'} description={pending?`This changes authoring access for ${pending.row.professional_name}.`:''} confirmLabel="Confirm decision" confirmTone={pending?.decision==='approved'?'primary':'danger'} busy={saving} onCancel={()=>{setPending(null);setNotes('');}} onConfirm={()=>void decide()}><label className="mt-4 block text-sm font-bold">Review notes <span className="text-danger-600">*</span><textarea autoFocus required minLength={5} rows={3} value={notes} onChange={event=>setNotes(event.target.value)} className="mt-2 w-full rounded-xl border p-3 font-normal"/></label></ConfirmDialog></div>;
}

function Action({label,icon,onClick,primary=false,danger=false}:{label:string;icon:ReactElement;onClick:()=>void;primary?:boolean;danger?:boolean}){return <button type="button" onClick={onClick} className={`inline-flex min-h-11 items-center gap-2 rounded-xl px-4 font-bold ${primary?'bg-success-600 text-white':danger?'border border-danger-200 text-danger-700':'border'}`}><span className="[&>svg]:h-4 [&>svg]:w-4">{icon}</span>{label}</button>;}
