import { useCallback, useEffect, useState } from 'react';
import { CheckCircle2, Loader2, RotateCcw, XCircle } from 'lucide-react';
import { Link } from 'react-router-dom';
import { AdminSidebar } from '../../components/admin/AdminSidebar';
import { supabase } from '../../lib/supabase';

interface Row { course_id: string; title: string; author_name: string | null; submitted_at: string }
export function AdminCourseReviews() {
  const [sidebar, setSidebar] = useState(false); const [rows, setRows] = useState<Row[]>([]); const [loading, setLoading] = useState(true); const [notes, setNotes] = useState<Record<string, string>>({}); const [message, setMessage] = useState('');
  const load = useCallback(async () => { const { data, error } = await supabase.rpc('admin_list_course_reviews'); setRows((data || []) as Row[]); if (error) setMessage('The review queue could not be loaded.'); setLoading(false); }, []); useEffect(() => { void load(); }, [load]);
  const decide = async (id: string, decision: string) => { const { error } = await supabase.rpc('admin_decide_course_review', { p_course_id: id, p_decision: decision, p_notes: notes[id] || '' }); setMessage(error ? error.message : `Course ${decision.replace('_', ' ')}.`); if (!error) await load(); };
  return <div className="min-h-screen bg-primary-50"><AdminSidebar isOpen={sidebar} setIsOpen={setSidebar} /><main className="px-4 pb-20 pt-20 lg:pl-72 lg:pt-8"><div className="mx-auto max-w-5xl"><header className="mb-7"><p className="font-bold text-amber-700">Quality governance</p><h1 className="text-3xl font-bold">Course review queue</h1><p className="mt-2 text-primary-600">Approve publication-ready courses or return actionable feedback to the instructor.</p></header>{message && <p role="status" className="mb-4 rounded-xl border bg-white p-3">{message}</p>}{loading ? <Loader2 className="mx-auto h-8 w-8 animate-spin" /> : rows.length === 0 ? <div className="rounded-2xl border border-dashed bg-white p-12 text-center">No courses are waiting for review.</div> : <div className="space-y-4">{rows.map(row => <article key={row.course_id} className="rounded-2xl border bg-white p-5 shadow-sm"><div className="flex flex-col gap-2 sm:flex-row sm:items-start sm:justify-between"><div><h2 className="text-xl font-bold">{row.title}</h2><p className="text-sm text-primary-500">{row.author_name || 'Instructor'} · Submitted {new Date(row.submitted_at).toLocaleString()}</p></div><Link to={`/admin/courses/${row.course_id}/builder`} className="font-bold text-accent-700">Inspect course</Link></div><label className="mt-4 block text-sm font-bold">Review notes<textarea rows={3} value={notes[row.course_id] || ''} onChange={event => setNotes(value => ({ ...value, [row.course_id]: event.target.value }))} placeholder="Required when requesting changes or rejecting" className="mt-2 w-full rounded-xl border p-3 font-normal" /></label><div className="mt-3 flex flex-wrap gap-2"><button type="button" onClick={() => void decide(row.course_id, 'approved')} className="inline-flex min-h-11 items-center gap-2 rounded-xl bg-success-600 px-4 font-bold text-white"><CheckCircle2 className="h-4 w-4" />Approve</button><button type="button" onClick={() => void decide(row.course_id, 'changes_requested')} className="inline-flex min-h-11 items-center gap-2 rounded-xl border px-4 font-bold"><RotateCcw className="h-4 w-4" />Request changes</button><button type="button" onClick={() => void decide(row.course_id, 'rejected')} className="inline-flex min-h-11 items-center gap-2 rounded-xl border border-danger-200 px-4 font-bold text-danger-700"><XCircle className="h-4 w-4" />Reject</button></div></article>)}</div>}</div></main></div>;
}
