import { useCallback, useEffect, useState } from 'react';
import { CheckCircle, GraduationCap, Loader2, XCircle } from 'lucide-react';
import { AdminSidebar } from '../../components/admin/AdminSidebar';
import { ConfirmDialog } from '../../components/admin/ConfirmDialog';
import { supabase } from '../../lib/supabase';

export function AdminInstructorApplications() {
  const [sidebar, setSidebar] = useState(false); const [rows, setRows] = useState<any[]>([]); const [loading, setLoading] = useState(true); const [pending, setPending] = useState<{ row: any; decision: string } | null>(null); const [notes, setNotes] = useState(''); const [saving, setSaving] = useState(false); const [message, setMessage] = useState('');
  const load = useCallback(async () => { setLoading(true); setMessage(''); const { data, error } = await supabase.rpc('admin_list_instructor_applications'); setRows(Array.isArray(data) ? data : []); if (error) setMessage(`Unable to load instructor applications (${error.code || 'request_failed'}).`); setLoading(false); }, []);
  useEffect(() => { void load(); }, [load]);
  const decide = async () => { if (!pending || notes.trim().length < 3) return; setSaving(true); const { error } = await supabase.rpc('admin_review_instructor_application', { p_application_id: pending.row.id, p_decision: pending.decision, p_notes: notes }); setSaving(false); if (error) setMessage(error.message); else { setMessage(`Application ${pending.decision.replace('_', ' ')}.`); setPending(null); setNotes(''); await load(); } };
  return <div className="min-h-screen bg-primary-50"><AdminSidebar isOpen={sidebar} setIsOpen={setSidebar} /><main className="px-4 pb-24 pt-20 lg:pl-72 lg:pt-8"><div className="mx-auto max-w-6xl"><header className="mb-8"><p className="font-bold text-amber-700">Quality review</p><h1 className="text-3xl font-bold text-primary-900">Instructor applications</h1><p className="mt-2 text-primary-600">Review professional background before granting course-authoring access.</p></header>{message && <p role="status" className="mb-5 rounded-xl border bg-white p-4">{message}</p>}{loading ? <Loader2 className="mx-auto h-8 w-8 animate-spin" /> : rows.length === 0 ? <div className="rounded-2xl border border-dashed bg-white p-12 text-center"><GraduationCap className="mx-auto mb-3 h-10 w-10 text-primary-300" /><p className="font-bold">No instructor applications</p></div> : <div className="space-y-4">{rows.map(row => <article key={row.id} className="rounded-2xl border border-primary-200 bg-white p-5 shadow-sm"><div className="flex flex-col gap-4 md:flex-row md:justify-between"><div><div className="flex flex-wrap items-center gap-2"><h2 className="text-xl font-bold text-primary-900">{row.professional_name}</h2><span className="rounded-full bg-primary-100 px-3 py-1 text-xs font-bold">{row.status}</span></div><p className="mt-1 text-sm text-primary-500">{row.applicant?.email}</p><p className="mt-4 max-w-3xl text-primary-700">{row.bio}</p><p className="mt-3 text-sm"><strong>Credentials:</strong> {row.credentials}</p><div className="mt-3 flex flex-wrap gap-2">{(row.expertise || []).map((item: string) => <span key={item} className="rounded-full bg-amber-50 px-3 py-1 text-xs font-bold text-amber-800">{item}</span>)}</div></div><div className="flex flex-none gap-2"><button type="button" onClick={() => setPending({ row, decision: 'approved' })} className="inline-flex min-h-11 items-center gap-2 rounded-xl bg-success-600 px-4 font-bold text-white"><CheckCircle className="h-4 w-4" />Approve</button><button type="button" onClick={() => setPending({ row, decision: 'changes_requested' })} className="inline-flex min-h-11 items-center gap-2 rounded-xl border border-danger-200 px-4 font-bold text-danger-700"><XCircle className="h-4 w-4" />Request changes</button></div></div></article>)}</div>}</div></main>{pending && <ConfirmDialog open title={pending.decision === 'approved' ? 'Approve instructor?' : 'Request changes?'} description={`${pending.row.professional_name} will be notified of this review state.`} confirmLabel={pending.decision === 'approved' ? 'Approve instructor' : 'Request changes'} confirmTone={pending.decision === 'approved' ? 'primary' : 'danger'} busy={saving} onCancel={() => setPending(null)} onConfirm={() => void decide()}><label className="mt-4 block text-sm font-bold">Review notes<textarea autoFocus rows={3} value={notes} onChange={event => setNotes(event.target.value)} className="mt-2 w-full rounded-xl border p-3 font-normal" /></label></ConfirmDialog>}</div>;
}
