import { useCallback, useEffect, useState } from 'react';
import { AlertCircle, CheckCircle2, Loader2, Send } from 'lucide-react';
import { supabase } from '../../../lib/supabase';
import { useAuth } from '../../../contexts/AuthContext';

interface Readiness { ready: boolean; checks: { key: string; label: string; complete: boolean }[]; review_status: string; authoring_status: string; status: string; reviewer_notes: string | null }

export function CourseReviewPanel({ courseId }: { courseId: string }) {
  const { user } = useAuth(); const isAdmin = user?.role === 'admin';
  const [data, setData] = useState<Readiness | null>(null); const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(false); const [message, setMessage] = useState('');
  const load = useCallback(async () => { const { data: readiness, error } = await supabase.rpc('get_course_readiness', { p_course_id: courseId }); setData((readiness || null) as Readiness | null); if (error) setMessage('Readiness checks could not be loaded.'); setLoading(false); }, [courseId]);
  useEffect(() => { void load(); }, [load]);
  const submit = async () => { setBusy(true); const { error } = await supabase.rpc('submit_course_for_review', { p_course_id: courseId, p_notes: '' }); setBusy(false); setMessage(error ? error.message : 'Course submitted. Editing is locked while an administrator reviews it.'); if (!error) await load(); };
  const publication = async (publish: boolean) => { setBusy(true); const { error } = await supabase.rpc('admin_set_course_publication', { p_course_id: courseId, p_publish: publish }); setBusy(false); setMessage(error ? error.message : publish ? 'Course published.' : 'Course unpublished.'); if (!error) await load(); };
  if (loading) return <p role="status" className="flex items-center gap-2"><Loader2 className="h-5 w-5 animate-spin" />Checking course readiness…</p>;
  if (!data) return <p role="alert">{message}</p>;
  return <div className="space-y-5"><div><h2 className="text-xl font-bold">Review and publication</h2><p className="mt-1 text-sm text-primary-600">Instructors submit completed drafts for review. Only an administrator can approve and publish a course.</p></div>{message && <p role="status" className="rounded-xl bg-primary-50 p-3 text-sm">{message}</p>}{data.reviewer_notes && <div className="rounded-xl border border-amber-200 bg-amber-50 p-4"><p className="font-bold">Reviewer feedback</p><p className="mt-1 whitespace-pre-wrap text-sm">{data.reviewer_notes}</p></div>}<div className="grid gap-3 sm:grid-cols-2">{data.checks.map(check => <div key={check.key} className={`flex min-h-14 items-center gap-3 rounded-xl border p-3 ${check.complete ? 'border-success-200 bg-success-100' : 'border-amber-200 bg-amber-50'}`}>{check.complete ? <CheckCircle2 className="h-5 w-5 text-success-700" /> : <AlertCircle className="h-5 w-5 text-amber-700" />}<span className="font-bold">{check.label}</span></div>)}</div><div className="flex flex-col gap-3 border-t pt-5 sm:flex-row"><span className="rounded-full bg-primary-100 px-4 py-2 text-center text-sm font-bold">Review: {data.review_status.replace('_', ' ')}</span>{!isAdmin && data.authoring_status === 'draft' && <button type="button" disabled={!data.ready || busy} onClick={() => void submit()} className="inline-flex min-h-11 items-center justify-center gap-2 rounded-xl bg-primary-900 px-5 font-bold text-white disabled:opacity-40"><Send className="h-4 w-4" />Submit for review</button>}{isAdmin && data.review_status === 'approved' && <button type="button" disabled={busy} onClick={() => void publication(data.status !== 'published')} className="min-h-11 rounded-xl bg-success-600 px-5 font-bold text-white">{data.status === 'published' ? 'Unpublish course' : 'Publish approved course'}</button>}</div></div>;
}
