import { useEffect, useState } from 'react';
import { Loader2, Search, UserCheck } from 'lucide-react';
import { supabase } from '../../../lib/supabase';

interface InstructorOption { user_id: string; professional_name: string; email: string; expertise: string[]; }

export function InstructorPicker({ value, onChange }: { value: string; onChange: (id: string) => void }) {
  const [query, setQuery] = useState(''); const [results, setResults] = useState<InstructorOption[]>([]); const [loading, setLoading] = useState(false); const [selected, setSelected] = useState<InstructorOption | null>(null);
  useEffect(() => { const timeout = window.setTimeout(async () => { setLoading(true); const { data } = await supabase.rpc('admin_search_approved_instructors', { p_query: query, p_limit: 20 }); const options = (data || []) as InstructorOption[]; setResults(options); if (value) setSelected(current => current?.user_id === value ? current : options.find(option => option.user_id === value) || current); setLoading(false); }, 300); return () => clearTimeout(timeout); }, [query, value]);
  return <div><label htmlFor="instructor-search" className="mb-2 block text-sm font-bold text-primary-900">Assigned instructor</label>{selected && value ? <div className="mb-3 flex items-center justify-between rounded-xl border border-success-200 bg-success-100 p-3"><div><p className="font-bold text-primary-900">{selected.professional_name}</p><p className="text-sm text-primary-600">{selected.email}</p></div><button type="button" onClick={() => { onChange(''); setSelected(null); }} className="min-h-10 rounded-lg border bg-white px-3 text-sm font-bold">Change</button></div> : <><div className="relative"><Search className="absolute left-3 top-1/2 h-5 w-5 -translate-y-1/2 text-primary-400" /><input id="instructor-search" type="search" value={query} onChange={event => setQuery(event.target.value)} placeholder="Search approved instructors by name or email" className="min-h-11 w-full rounded-xl border border-primary-200 bg-primary-50 py-2 pl-10 pr-10" />{loading && <Loader2 className="absolute right-3 top-1/2 h-4 w-4 -translate-y-1/2 animate-spin" />}</div><div className="mt-2 max-h-52 overflow-y-auto rounded-xl border border-primary-100">{results.map(option => <button type="button" key={option.user_id} onClick={() => { onChange(option.user_id); setSelected(option); }} className="flex min-h-14 w-full items-center gap-3 border-b border-primary-100 p-3 text-left last:border-0 hover:bg-primary-50"><UserCheck className="h-5 w-5 flex-none text-success-600" /><span><span className="block font-bold text-primary-900">{option.professional_name}</span><span className="block text-sm text-primary-500">{option.email}</span></span></button>)}{!loading && results.length === 0 && <p className="p-4 text-sm text-primary-500">No approved instructors match your search.</p>}</div></>}<p className="mt-2 text-xs text-primary-500">Only admin-approved, active instructors can be assigned.</p></div>;
}
